.PHONY: help build test security security-go security-frontend proto lint-plugins lint-plugins-self-test lint lint-go-fmt

help:
	@echo "Targets:"
	@echo "  build                      go build ./..."
	@echo "  test                       go test -race ./..."
	@echo "  security                   run all security scans (govulncheck + npm audit)"
	@echo "  security-go                govulncheck ./..."
	@echo "  security-frontend          npm audit --omit=dev (in frontend/)"
	@echo "  proto                      regenerate plugin-sdk/gen/ from .proto sources (requires buf)"
	@echo "  lint-plugins               enforce /plugins/* import boundary"
	@echo "  lint-plugins-self-test     prove the lint catches a deliberate violation"
	@echo "  lint                       run all lint checks (gofmt + import boundary)"
	@echo "  lint-go-fmt                fail if any tracked .go file is not gofmt-clean"

build:
	go build ./...

test:
	go test -race ./...

security: security-go security-frontend

security-go:
	govulncheck ./...

security-frontend:
	cd frontend && npm audit --omit=dev

# Regenerate gRPC/protobuf stubs from .proto sources.
# Requires buf: https://buf.build/docs/installation
# Pinned plugin versions are declared in buf.gen.yaml.
# The proto-gen-drift CI job ensures checked-in stubs are never stale.
proto:
	buf generate

lint-plugins:
	./scripts/lint-plugins.sh

lint-plugins-self-test:
	./scripts/lint-plugins-self-test.sh

# lint is the human-facing aggregate: run both gofmt and import-boundary checks.
# CI calls the granular targets (lint-go-fmt, lint-plugins) directly.
lint: lint-go-fmt lint-plugins

# Fail if any tracked .go file is not gofmt-canonical.
# gen/ is excluded because those files are regenerated by buf (proto stubs);
# stale-gen drift is already caught by the proto-gen-drift CI job.
# *.go.tmpl scaffold files are not matched by *.go so need no explicit exclusion.
# NOTE: $$(…) escapes Make's variable expansion so command substitution runs in
# the shell; $$unformatted likewise escapes the shell variable reference.
# All lines end with ; \ so the entire recipe executes in ONE shell invocation
# (otherwise the variable set in line 1 would be invisible to line 2+).
lint-go-fmt:
	@unformatted=$$(gofmt -l $$(git ls-files '*.go' | grep -v '/gen/')); \
	if [ -n "$$unformatted" ]; then \
		echo "gofmt needed (run: gofmt -w <file>):"; \
		echo "$$unformatted"; \
		exit 1; \
	fi
