package main

import (
	"gopkg.in/yaml.v3"

	"github.com/felag-engineering/gleipnir/plugin-sdk/manifest"
)

// pluginManifest declares the Slack plugin's metadata and capabilities.
// manifest.yaml is its canonical YAML projection — generated by manifest.Marshal,
// never hand-written. Run `make manifest` to regenerate it.
var pluginManifest = manifest.Manifest{
	SchemaVersion: "v1",
	Name:          "slack",
	Version:       "0.1.0",
	Description:   "Slack integration: tools (send/list channels), triggers (channel messages), and channels (notify/request via Slack DMs and posts).",
	Services: manifest.Services{
		Tool:    "v1",
		Trigger: "v1",
		Channel: "v1",
	},
	// oauth2_authcode strategy: the host runs the OAuth2 authorization code flow
	// on behalf of the plugin and stores the resulting access + refresh token pair
	// in credentials_encrypted (spec §9.2).
	//
	// HasClientID and HasClientSecret are presence booleans, not values — setting
	// either to true makes the key appear in the YAML (omitempty suppresses false).
	// Setting both true advertises that this strategy requires a client_id and
	// client_secret to be populated at install time by an admin. The actual
	// credentials live in encrypted storage, never in the manifest file.
	Auth: manifest.AuthDecl{
		Mode:     "instance_credentials",
		Strategy: manifest.AuthStrategyOAuth2Authcode,
		OAuthDefaults: &manifest.OAuthDefaultsDecl{
			AuthorizationURL: "https://slack.com/oauth/v2/authorize",
			TokenURL:         "https://slack.com/api/oauth.v2.access",
			Scopes:           []string{"channels:read", "chat:write", "im:write", "users:read"},
			HasClientID:      true,
			HasClientSecret:  true,
		},
	},
	// Tools is empty for this scaffold; #233 will populate it with
	// send_message, list_channels, and related tool declarations.
	Tools: nil,
	// ConfigSchema is omitted for this scaffold. Instance-level config
	// (workspace ID, default channel, etc.) lands in #236 with OAuth wiring.
	Channels: []manifest.ChannelDecl{
		{
			ImplementsNotify:  true,
			ImplementsRequest: true,
			// channel_config_schema: per-audience-entry config operators set when
			// adding a Slack audience entry to a policy.
			ConfigSchema: mustParseYAML(`
type: object
required:
  - channel
properties:
  channel:
    type: string
    description: 'Slack channel or user DM target (e.g. #general or @username)'
  mention:
    type: string
    description: Slack user or group to mention in the message (e.g. @oncall)
`),
		},
	},
}

// SlackChannelMessageBinding is the per-policy binding struct for the
// channel_message event kind. Fields drive the binding_schema shown in the
// policy trigger editor. #234 fills in the matching TriggerService.Start logic.
type SlackChannelMessageBinding struct {
	// Channel is a glob pattern matched against the Slack channel name. Use
	// GlobField so the binding evaluator selects OpGlob at runtime.
	Channel manifest.GlobField `json:"channel,omitempty" jsonschema:"title=Channel,description=Glob pattern matched against the Slack channel name (e.g. #incidents-*)"`
	// Text is a substring matched against the message text. Use ContainsField so
	// the binding evaluator selects OpContains at runtime.
	Text manifest.ContainsField `json:"text,omitempty" jsonschema:"title=Text contains,description=Substring matched against the message text"`
}

// SlackChannelEntryConfig documents the Go-side shape of the per-audience-entry
// config validated against the ConfigSchema above. The actual schema is parsed
// from the YAML literal; this struct exists for code readability only.
// #235 will use this type when implementing ChannelService.Request.
type SlackChannelEntryConfig struct {
	Channel string `json:"channel"` // required
	Mention string `json:"mention"` // optional
}

func init() {
	// channel_message is the event kind emitted whenever a message is posted to
	// a watched Slack channel. The binding_schema is derived by reflection from
	// SlackChannelMessageBinding so the policy editor renders the GlobField and
	// ContainsField correctly. #234 implements the matching TriggerService.Start.
	pluginManifest.MustAddEventKind(
		"channel_message",
		"A message was posted to a Slack channel",
		SlackChannelMessageBinding{},
		nil, // payloadSchema: #234 will add a typed payload schema
	)
}

// mustParseYAML parses a YAML string into a *yaml.Node. It panics on error
// because these are compile-time literals in the manifest declaration.
func mustParseYAML(src string) *yaml.Node {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		panic("mustParseYAML: " + err.Error())
	}
	// yaml.Unmarshal returns a document node; return its first content child.
	if doc.Kind == yaml.DocumentNode && len(doc.Content) > 0 {
		return doc.Content[0]
	}
	return &doc
}
