package main

import (
	"github.com/invopop/jsonschema"
	"gopkg.in/yaml.v3"

	"github.com/felag-engineering/gleipnir/plugin-sdk/manifest"
)

// pluginManifest declares the Slack plugin's metadata and capabilities.
// manifest.yaml is its canonical YAML projection — generated by manifest.Marshal,
// never hand-written. Run `make manifest` to regenerate it.
var pluginManifest = manifest.Manifest{
	SchemaVersion: "v1",
	Name:          "slack",
	Version:       "0.1.1",
	Description:   "Slack integration: tools (send/list channels), triggers (channel messages), and channels (notify/request via Slack DMs and posts).",
	Services: manifest.Services{
		Tool:    "v1",
		Trigger: "v1",
		Channel: "v1",
	},
	// oauth2_authcode strategy: the host runs the OAuth2 authorization code flow
	// on behalf of the plugin and stores the resulting access + refresh token pair
	// in credentials_encrypted (spec §9.2).
	Auth: manifest.AuthDecl{
		Mode:     "instance_credentials",
		Strategy: manifest.AuthStrategyOAuth2Authcode,
		OAuthDefaults: &manifest.OAuthDefaultsDecl{
			AuthorizationURL: "https://slack.com/oauth/v2/authorize",
			TokenURL:         "https://slack.com/api/oauth.v2.access",
			// Sequences are NOT sorted by manifest.Marshal (yaml.go:85-89);
			// declare in alphabetical order to keep manifest.yaml byte-stable for
			// TestManifestYAMLIsCanonical.
			//
			// The four *:history scopes (channels:history, groups:history,
			// im:history, mpim:history) are reserved for future history-reading
			// tools (e.g. conversations.history). The current plugin code does NOT
			// call these endpoints. Socket Mode delivery (TriggerService) uses the
			// app-level xapp- token and does NOT require these bot-token scopes.
			// They are requested up-front so the same OAuth grant covers planned
			// tools without a re-authorize round trip.
			Scopes: []string{
				"channels:history",
				"channels:read",
				"chat:write",
				"groups:history",
				"im:history",
				"im:write",
				"mpim:history",
				"users:read",
			},
			// HasClientID and HasClientSecret describe whether the manifest carries
			// default values. OAuthDefaultsDecl has no string fields for those
			// (plugin-sdk/manifest/manifest.go:208-224). Per PR #236 (user
			// Option A), we intentionally ship no defaults — operators register
			// their own Slack app and supply client_id/client_secret per-instance
			// via the admin UI (consumed by oauth.Resolve via InstanceConfigOverride
			// at internal/plugin/oauth/credentials.go:201-238). Setting these
			// honestly to false reflects the SDK's documented semantic; no host
			// behavior depends on the values.
			HasClientID:     false,
			HasClientSecret: false,
		},
	},
	Tools: buildToolDecls(),
	// ConfigSchema declares required instance-level config. The app_level_token
	// (xapp- prefix) is the Socket Mode token used by TriggerService; it is
	// separate from the OAuth bot token stored in credentials_encrypted.
	// x-gleipnir-secret: true causes the host to redact this field to "***"
	// on every GET response (ADR-049).
	ConfigSchema: mustParseYAML(`
type: object
required:
  - app_level_token
properties:
  app_level_token:
    type: string
    x-gleipnir-secret: true
    description: 'Slack app-level token (xapp- prefix) for Socket Mode. Generate in Slack admin: Settings → Socket Mode → Generate token with scope connections:write.'
`),
	Channels: []manifest.ChannelDecl{
		{
			ImplementsNotify:  true,
			ImplementsRequest: true,
			// channel_config_schema: per-audience-entry config operators set when
			// adding a Slack audience entry to a policy.
			ConfigSchema: mustParseYAML(`
type: object
required:
  - channel
properties:
  channel:
    type: string
    description: 'Slack channel or user DM target (e.g. #general or @username)'
  mention:
    type: string
    description: Slack user or group to mention in the message (e.g. @oncall)
  response_buttons:
    type: array
    description: Custom response buttons for Request messages. Defaults to Approve/Reject if omitted.
    items:
      type: object
      required:
        - option_id
        - label
        - value
      properties:
        option_id:
          type: string
          description: Unique identifier for this button option (echoed in feedback_response payload)
        label:
          type: string
          description: Button label text displayed to the operator
        value:
          type: string
          description: Value echoed in feedback_response payload
        style:
          type: string
          enum:
            - default
            - primary
            - danger
          description: 'Button colour: primary (green), danger (red), or default (no colour)'
`),
		},
	},
}

// buildToolDecls returns the four Slack tool declarations for the manifest.
// InputSchema is a *yaml.Node (manifest.ToolDecl.InputSchema, manifest.go:237)
// produced by manifest.MustReflectSchema — distinct from the JSON-string form
// used by ToolService.ListTools on the wire (see tools.go:reflectInputSchemaJSON).
// Tool names are unqualified; the host prepends the instance name at runtime
// (internal/plugin/tools/registrar.go:72).
func buildToolDecls() []manifest.ToolDecl {
	return []manifest.ToolDecl{
		{
			Name:        "post_message",
			Description: "Post a plain-text message to a Slack channel or DM.",
			InputSchema: manifest.MustReflectSchema(PostMessageParams{}),
		},
		{
			Name:        "list_channels",
			Description: "List Slack channels visible to the bot user.",
			InputSchema: manifest.MustReflectSchema(ListChannelsParams{}),
		},
		{
			Name:        "react",
			Description: "Add an emoji reaction to a Slack message.",
			InputSchema: manifest.MustReflectSchema(ReactParams{}),
		},
		{
			Name:        "set_topic",
			Description: "Set the topic of a Slack channel.",
			InputSchema: manifest.MustReflectSchema(SetTopicParams{}),
		},
	}
}

// SlackChannelID is a typed Slack channel identifier (e.g. "C012ABCDEF").
// Names are not accepted: Socket Mode message events only carry the channel
// ID, so a name-based scope would silently never match (see scope_test.go).
// The emitted JSON Schema carries a pattern that rejects non-ID strings at
// save time via the host's configvalidate pipeline.
type SlackChannelID string

// JSONSchema implements the invopop/jsonschema.SchemaCustomizer interface so
// that ReflectSchema emits {type: string, pattern: "^C[A-Z0-9]+$"} — Slack
// channel IDs start with a capital C followed by alphanumerics.
func (SlackChannelID) JSONSchema() *jsonschema.Schema {
	return &jsonschema.Schema{Type: "string", Pattern: "^C[A-Z0-9]+$"}
}

// SlackSubscriptionScope is the instance-level coarse subscription filter sent
// in TriggerService.Start as watch_scope_json. It limits which channels the
// plugin watches across ALL policies on this instance, reducing noise from
// high-traffic channels like #general.
//
// Distinct from SlackChannelMessageBinding (per-policy event filter): scope is
// configured once on the instance; binding is configured per-policy.
type SlackSubscriptionScope struct {
	// Channels is a list of Slack channel IDs to watch (e.g. "C012ABCDEF").
	// Empty means watch all channels the bot is a member of. Channel names
	// (e.g. "#incidents") are rejected — Socket Mode events carry only IDs,
	// so a name-based scope never matches. Find a channel's ID in Slack via
	// channel settings → About → Channel ID.
	Channels []SlackChannelID `json:"channels,omitempty" jsonschema:"title=Channels,description=Slack channel IDs (e.g. C012ABCDEF). Empty = watch all. Find IDs in channel settings → About → Channel ID."`
	// MentionOnly limits delivery to messages where the bot is mentioned.
	MentionOnly bool `json:"mention_only,omitempty" jsonschema:"title=Mention-only,description=Only emit when bot is mentioned."`
}

// SlackChannelMessageBinding is the per-policy binding struct for the
// channel_message event kind. Fields drive the binding_schema shown in the
// policy trigger editor.
type SlackChannelMessageBinding struct {
	// Channel is a substring matched against the Slack channel name or ID.
	// ContainsField is used here rather than GlobField: the host binding evaluator
	// rejects format:glob (binding.go:230), but accepts format:contains.
	Channel manifest.ContainsField `json:"channel,omitempty" jsonschema:"title=Channel,description=Substring matched against the Slack channel name or ID (e.g. #incidents)"`
	// Text is a substring matched against the message text.
	Text manifest.ContainsField `json:"text,omitempty" jsonschema:"title=Text contains,description=Substring matched against the message text"`
	// MentionOnly restricts the policy to events where the bot was mentioned.
	MentionOnly bool `json:"mention_only,omitempty" jsonschema:"title=Mention-only,description=Only trigger when the bot is mentioned in the message"`
	// User restricts the policy to messages from a specific Slack user ID.
	User manifest.EqualsField `json:"user,omitempty" jsonschema:"title=User,description=Slack user ID to match (e.g. U012AB3CD). Leave empty to match all users."`
}

// SlackChannelMessagePayload is the JSON payload emitted for each channel_message
// event. The host binding evaluator matches policy bindings against these fields.
// Fields marked omitempty are absent when the Slack event does not include them.
//
// yaml tags mirror the json tags so that yaml.Marshal (used for manifest examples)
// produces underscore-separated keys matching the JSON wire format. Without explicit
// yaml tags, yaml.v3 would use all-lowercase camelCase (e.g. "channelid" instead
// of "channel_id"), making examples misleading in the admin UI.
type SlackChannelMessagePayload struct {
	// Channel is the display name (best-effort) or channel ID when the name is unknown.
	Channel string `json:"channel" yaml:"channel" jsonschema:"title=Channel,description=Channel display name (e.g. #incidents) or channel ID when the name is unknown"`
	// ChannelID is the stable Slack channel identifier (always present).
	ChannelID string `json:"channel_id" yaml:"channel_id" jsonschema:"title=Channel ID,description=Stable Slack channel identifier (e.g. C01ABC)"`
	// Text is the plain-text message body.
	Text string `json:"text" yaml:"text" jsonschema:"title=Text,description=Plain-text message body"`
	// User is the Slack user ID of the sender (empty for bot/system messages).
	User string `json:"user,omitempty" yaml:"user,omitempty" jsonschema:"title=User,description=Slack user ID of the sender (empty for bot/system messages)"`
	// Ts is the Slack message timestamp (uniquely identifies the message within a channel).
	Ts string `json:"ts" yaml:"ts" jsonschema:"title=Timestamp,description=Slack message timestamp (uniquely identifies the message within a channel)"`
	// ThreadTs is the parent thread timestamp (present only for threaded replies).
	ThreadTs string `json:"thread_ts,omitempty" yaml:"thread_ts,omitempty" jsonschema:"title=Thread timestamp,description=Parent thread timestamp (present only for threaded replies)"`
	// EventTs is the timestamp of the event itself.
	EventTs string `json:"event_ts" yaml:"event_ts" jsonschema:"title=Event timestamp,description=Timestamp of the event itself"`
	// TeamID is the Slack workspace (team) ID (best-effort; may be empty for some event shapes).
	TeamID string `json:"team_id,omitempty" yaml:"team_id,omitempty" jsonschema:"title=Team ID,description=Slack workspace ID (best-effort; may be empty for some event shapes)"`
	// ChannelType indicates the channel kind (channel, group, im, mim).
	ChannelType string `json:"channel_type" yaml:"channel_type" jsonschema:"title=Channel type,description=Slack channel kind: channel (public)\\, group (private)\\, im (DM)\\, mim (multi-DM)"`
	// Mentioned is true when the bot was mentioned in the message (app_mention event).
	Mentioned bool `json:"mentioned" yaml:"mentioned" jsonschema:"title=Mentioned,description=True when the bot was explicitly mentioned in the message"`
}

// SlackChannelEntryConfig documents the Go-side shape of the per-audience-entry
// config validated against the ConfigSchema above. The actual schema is parsed
// from the YAML literal; this struct exists for code readability only.
type SlackChannelEntryConfig struct {
	Channel         string           `json:"channel"`                    // required
	Mention         string           `json:"mention,omitempty"`          // optional
	ResponseButtons []responseButton `json:"response_buttons,omitempty"` // optional; defaults applied in Go
}

func init() {
	// SubscriptionSchema defines the instance-level coarse filter passed in
	// TriggerService.Start as watch_scope_json. Operators configure this once
	// per plugin instance to limit which channels are watched.
	pluginManifest.SubscriptionSchema = manifest.MustReflectSchema(SlackSubscriptionScope{})

	// channel_message is the event kind emitted whenever a message is posted to
	// a watched Slack channel. The binding_schema and payload_schema are derived
	// by reflection so the policy editor renders the fields correctly.
	// Three example payloads are provided for the "Test against sample" UI (spec §7.5).
	pluginManifest.MustAddEventKindWithExamples(
		"channel_message",
		"A message was posted to a Slack channel",
		SlackChannelMessageBinding{},
		manifest.MustReflectSchema(SlackChannelMessagePayload{}),
		manifest.Example{
			Name: "Plain channel message",
			Payload: SlackChannelMessagePayload{
				Channel:     "#general",
				ChannelID:   "C012ABCDEF",
				Text:        "Lunch order is in.",
				User:        "U01USER001",
				Ts:          "1700000001.000100",
				EventTs:     "1700000001.000100",
				TeamID:      "T03TEAM001",
				ChannelType: "channel",
				Mentioned:   false,
			},
		},
		manifest.Example{
			Name: "Bot mention in incidents channel",
			Payload: SlackChannelMessagePayload{
				Channel:     "#incidents",
				ChannelID:   "C09INCIDENT",
				Text:        "<@U07BOTUSER> the database is degraded",
				User:        "U01USER002",
				Ts:          "1700001000.000200",
				EventTs:     "1700001000.000200",
				TeamID:      "T03TEAM001",
				ChannelType: "channel",
				Mentioned:   true,
			},
		},
		manifest.Example{
			Name: "Threaded reply",
			Payload: SlackChannelMessagePayload{
				Channel:     "#ops",
				ChannelID:   "C09OPSCHAN",
				Text:        "Rolled back the deployment, monitoring now.",
				User:        "U01USER003",
				Ts:          "1700002000.000300",
				ThreadTs:    "1700002000.000100",
				EventTs:     "1700002000.000300",
				TeamID:      "T03TEAM001",
				ChannelType: "channel",
				Mentioned:   false,
			},
		},
	)
}

// mustParseYAML parses a YAML string into a *yaml.Node. It panics on error
// because these are compile-time literals in the manifest declaration.
func mustParseYAML(src string) *yaml.Node {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		panic("mustParseYAML: " + err.Error())
	}
	// yaml.Unmarshal returns a document node; return its first content child.
	if doc.Kind == yaml.DocumentNode && len(doc.Content) > 0 {
		return doc.Content[0]
	}
	return &doc
}
