package main

import (
	"gopkg.in/yaml.v3"

	"github.com/felag-engineering/gleipnir/plugin-sdk/manifest"
)

// pluginManifest declares the ntfy plugin's metadata and capabilities.
// manifest.yaml is its canonical YAML projection — generated by manifest.Marshal,
// never hand-written. Run gen_manifest_local.go to regenerate it.
var pluginManifest = manifest.Manifest{
	SchemaVersion: "v1",
	Name:          "ntfy",
	Version:       "0.1.0",
	Description:   "Sends notifications to an ntfy server via HTTP POST.",
	Services: manifest.Services{
		Channel: "v1",
	},
	// static_key strategy: the host stores an API key that the plugin retrieves
	// via GetCredentials. The credentials JSON shape is {"api_key":"<token>"}.
	// Spec §9.1 uses the conceptual name "static_api_key"; the manifest validator
	// uses the code-level name "static_key" (see plugin-sdk/manifest/manifest.go).
	Auth: manifest.AuthDecl{
		Mode:     "instance_credentials",
		Strategy: "static_key",
	},
	Channels: []manifest.ChannelDecl{
		{
			ImplementsNotify: true,
			// channel_config_schema: per-audience-entry config; operators can
			// override the default topic per audience entry.
			ConfigSchema: mustParseYAML(`
type: object
properties:
  topic:
    type: string
    description: "ntfy topic to publish to (overrides default_topic)"
`),
		},
	},
	// config_schema: instance-scoped configuration set once per install.
	// server_url is required; default_topic and auth_header_name are optional.
	ConfigSchema: mustParseYAML(`
type: object
required:
  - server_url
properties:
  auth_header_name:
    default: Authorization
    description: "HTTP header name for the API key (default: Authorization)"
    type: string
  default_topic:
    description: "Default ntfy topic when none is set on the audience entry"
    type: string
  server_url:
    description: "Base URL of the ntfy server (e.g. https://ntfy.sh)"
    format: uri
    type: string
`),
}

// mustParseYAML parses a YAML string into a *yaml.Node. It panics on error
// because these are compile-time literals in the manifest declaration.
func mustParseYAML(src string) *yaml.Node {
	var doc yaml.Node
	if err := yaml.Unmarshal([]byte(src), &doc); err != nil {
		panic("mustParseYAML: " + err.Error())
	}
	// yaml.Unmarshal returns a document node; return its first content child.
	if doc.Kind == yaml.DocumentNode && len(doc.Content) > 0 {
		return doc.Content[0]
	}
	return &doc
}
