package signing

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestVerifyOwnSignatureFromFixture parses fixture .minisig and .pub files and
// verifies the signature against the fixture payload.
//
// The fixtures were generated by our own library (see testdata/README.md), not
// by the upstream minisign binary. The actual upstream-interop guarantee is
// provided by the integration-tagged TestUpstreamCLIVerifiesOurSignature test.
func TestVerifyOwnSignatureFromFixture(t *testing.T) {
	payload, err := os.ReadFile("testdata/upstream_payload.bin")
	if err != nil {
		t.Fatalf("read payload: %v", err)
	}
	pubData, err := os.ReadFile("testdata/upstream.pub")
	if err != nil {
		t.Fatalf("read pub: %v", err)
	}
	sigData, err := os.ReadFile("testdata/upstream.minisig")
	if err != nil {
		t.Fatalf("read minisig: %v", err)
	}

	pk, _, err := ParsePublicKey(pubData)
	if err != nil {
		t.Fatalf("parse public key: %v", err)
	}
	sig, _, err := ParseSignature(sigData)
	if err != nil {
		t.Fatalf("parse signature: %v", err)
	}

	if err := Verify(pk, payload, sig, sig.TrustedComment); err != nil {
		t.Errorf("verify fixture: %v", err)
	}
}

// TestRoundTripParsesAsUpstreamLayout verifies the structural shape of our
// output: correct headers, base64-encoded lines, trusted/untrusted comment
// prefixes.
func TestRoundTripParsesAsUpstreamLayout(t *testing.T) {
	pk, sk, err := GenerateKeypair(nil)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	payload := []byte("test payload")
	comment := "timestamp:9999"
	sig, err := Sign(sk.SecretKey, sk.KeyID, payload, comment)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}

	pubData := MarshalPublicKey(pk, "test key")
	sigData := MarshalSignature(sig, "test sig")

	// Verify public key layout: 2 lines, first has "untrusted comment: " prefix.
	pubLines := strings.Split(strings.TrimRight(string(pubData), "\n"), "\n")
	if len(pubLines) != 2 {
		t.Errorf("public key: expected 2 lines, got %d", len(pubLines))
	}
	if !strings.HasPrefix(pubLines[0], "untrusted comment: ") {
		t.Errorf("public key line 1: expected 'untrusted comment: ' prefix, got %q", pubLines[0])
	}

	// Verify signature layout: 4 lines with correct headers.
	sigLines := strings.Split(strings.TrimRight(string(sigData), "\n"), "\n")
	if len(sigLines) != 4 {
		t.Errorf("signature: expected 4 lines, got %d", len(sigLines))
	}
	if !strings.HasPrefix(sigLines[0], "untrusted comment: ") {
		t.Errorf("sig line 1: expected 'untrusted comment: ' prefix")
	}
	if !strings.HasPrefix(sigLines[2], "trusted comment: ") {
		t.Errorf("sig line 3: expected 'trusted comment: ' prefix, got %q", sigLines[2])
	}
	if sigLines[2] != "trusted comment: "+comment {
		t.Errorf("trusted comment: got %q, want %q", sigLines[2], "trusted comment: "+comment)
	}

	// Re-parse and re-verify to confirm round-trip.
	parsedPK, _, err := ParsePublicKey(pubData)
	if err != nil {
		t.Fatalf("re-parse public key: %v", err)
	}
	parsedSig, _, err := ParseSignature(sigData)
	if err != nil {
		t.Fatalf("re-parse signature: %v", err)
	}
	if err := Verify(parsedPK, payload, parsedSig, comment); err != nil {
		t.Errorf("re-verify: %v", err)
	}
}

// TestOurSignatureVerifiesAsUpstreamLayout generates a keypair in-process,
// signs a known payload, writes .minisig and .pub to a tempdir, re-parses, and
// verifies. Confirms our output is a valid upstream-shaped artifact (AC#7
// format-shape compliance without upstream binary).
func TestOurSignatureVerifiesAsUpstreamLayout(t *testing.T) {
	pk, sk, err := GenerateKeypair(nil)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	payload := PluginPayload([]byte("fake binary"), []byte("name: test\nversion: 1.0.0\n"))
	comment := "timestamp:1234567890\tname:test-plugin\tversion:1.0.0"

	sig, err := Sign(sk.SecretKey, sk.KeyID, payload, comment)
	if err != nil {
		t.Fatalf("sign: %v", err)
	}

	dir := t.TempDir()
	pubPath := filepath.Join(dir, "signing.pub")
	sigPath := filepath.Join(dir, "myplugin.minisig")

	if err := os.WriteFile(pubPath, MarshalPublicKey(pk, "test key"), 0o644); err != nil {
		t.Fatalf("write pub: %v", err)
	}
	if err := os.WriteFile(sigPath, MarshalSignature(sig, "test sig"), 0o644); err != nil {
		t.Fatalf("write sig: %v", err)
	}

	// Re-read and verify from disk.
	pubData, err := os.ReadFile(pubPath)
	if err != nil {
		t.Fatalf("read pub: %v", err)
	}
	sigData, err := os.ReadFile(sigPath)
	if err != nil {
		t.Fatalf("read sig: %v", err)
	}

	parsedPK, _, err := ParsePublicKey(pubData)
	if err != nil {
		t.Fatalf("parse pub: %v", err)
	}
	parsedSig, _, err := ParseSignature(sigData)
	if err != nil {
		t.Fatalf("parse sig: %v", err)
	}

	if err := Verify(parsedPK, payload, parsedSig, comment); err != nil {
		t.Errorf("verify from disk: %v", err)
	}
}
