package configvalidate

import (
	"context"
	"crypto/sha256"
	"fmt"
	"sync"

	"github.com/felag-engineering/gleipnir/internal/db"
	sdkmanifest "github.com/felag-engineering/gleipnir/plugin-sdk/manifest"
)

// Snapshotter parses and caches plugin manifests by content hash.
//
// Intentional contract: the dispatcher trusts the persisted notify/request
// flags on audience entries without re-checking ChannelDecl at dispatch time.
// Write-time validation via ValidateChannelCapabilities is the sole gate that
// ensures those flags are consistent with the manifest.  Snapshotter is the
// read path that makes that validation cheap on hot paths.
type Snapshotter struct {
	q             ManifestQuerier
	manifestCache sync.Map // sha256([32]byte) → *sdkmanifest.Manifest
}

// ManifestQuerier is the narrow DB interface Snapshotter needs. It matches the
// signatures generated by sqlc.
type ManifestQuerier interface {
	GetPluginByID(ctx context.Context, id string) (db.Plugin, error)
	GetPluginInstanceByID(ctx context.Context, id string) (db.PluginInstance, error)
}

// NewSnapshotter returns a Snapshotter backed by q.
func NewSnapshotter(q ManifestQuerier) *Snapshotter {
	return &Snapshotter{q: q}
}

// ForPluginID returns the parsed manifest for the plugin with the given ID.
// The result is cached by content hash; a changed manifest_snapshot is
// detected automatically on the next call.
func (s *Snapshotter) ForPluginID(ctx context.Context, pluginID string) (*sdkmanifest.Manifest, error) {
	plugin, err := s.q.GetPluginByID(ctx, pluginID)
	if err != nil {
		return nil, fmt.Errorf("snapshotter: get plugin %s: %w", pluginID, err)
	}
	return s.parseAndCache([]byte(plugin.ManifestSnapshot))
}

// ForInstanceID resolves instance → plugin → manifest.
func (s *Snapshotter) ForInstanceID(ctx context.Context, instanceID string) (*sdkmanifest.Manifest, error) {
	inst, err := s.q.GetPluginInstanceByID(ctx, instanceID)
	if err != nil {
		return nil, fmt.Errorf("snapshotter: get instance %s: %w", instanceID, err)
	}
	return s.ForPluginID(ctx, inst.PluginID)
}

// ResetCache clears the process-level manifest cache.
//
// Test-only. Call between subtests that share the process to avoid pollution.
func (s *Snapshotter) ResetCache() {
	s.manifestCache.Range(func(k, _ any) bool {
		s.manifestCache.Delete(k)
		return true
	})
}

// parseAndCache parses raw manifest YAML bytes, caches by content hash, and
// returns the cached pointer on subsequent calls with identical bytes.
func (s *Snapshotter) parseAndCache(raw []byte) (*sdkmanifest.Manifest, error) {
	key := sha256.Sum256(raw)

	if v, ok := s.manifestCache.Load(key); ok {
		return v.(*sdkmanifest.Manifest), nil
	}

	var m sdkmanifest.Manifest
	if err := sdkmanifest.Unmarshal(raw, &m); err != nil {
		return nil, fmt.Errorf("snapshotter: parse manifest: %w", err)
	}

	actual, _ := s.manifestCache.LoadOrStore(key, &m)
	return actual.(*sdkmanifest.Manifest), nil
}
