// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_requests.sql

package db

import (
	"context"
)

const countPendingApprovalRequests = `-- name: CountPendingApprovalRequests :one
SELECT COUNT(*) FROM approval_requests WHERE status = 'pending'
`

func (q *Queries) CountPendingApprovalRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingApprovalRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (id, run_id, tool_name, proposed_input, reasoning_summary, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6, ?7)
RETURNING id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at, decided_by
`

type CreateApprovalRequestParams struct {
	ID               string `json:"id"`
	RunID            string `json:"run_id"`
	ToolName         string `json:"tool_name"`
	ProposedInput    string `json:"proposed_input"`
	ReasoningSummary string `json:"reasoning_summary"`
	ExpiresAt        string `json:"expires_at"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRowContext(ctx, createApprovalRequest,
		arg.ID,
		arg.RunID,
		arg.ToolName,
		arg.ProposedInput,
		arg.ReasoningSummary,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.ReasoningSummary,
		&i.Status,
		&i.DecidedAt,
		&i.ExpiresAt,
		&i.Note,
		&i.CreatedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at, decided_by FROM approval_requests WHERE id = ?1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error) {
	row := q.db.QueryRowContext(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.ReasoningSummary,
		&i.Status,
		&i.DecidedAt,
		&i.ExpiresAt,
		&i.Note,
		&i.CreatedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getPendingApprovalRequestsByRun = `-- name: GetPendingApprovalRequestsByRun :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at, decided_by FROM approval_requests
WHERE run_id = ?1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingApprovalRequestsByRun(ctx context.Context, runID string) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingApprovalRequestsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalDecidersByRun = `-- name: ListApprovalDecidersByRun :many
SELECT ar.id, ar.status, ar.decided_at, ar.decided_by, u.username AS decided_by_username
FROM approval_requests ar
LEFT JOIN users u ON u.id = ar.decided_by
WHERE ar.run_id = ?1
ORDER BY ar.created_at ASC
`

type ListApprovalDecidersByRunRow struct {
	ID                string  `json:"id"`
	Status            string  `json:"status"`
	DecidedAt         *string `json:"decided_at"`
	DecidedBy         *string `json:"decided_by"`
	DecidedByUsername *string `json:"decided_by_username"`
}

// ListApprovalDecidersByRun returns each approval of a run with the username of
// the user who decided it. decided_by is NULL for a timeout, a row that predates
// the column, or a since-deleted account; LEFT JOIN keeps those rows.
func (q *Queries) ListApprovalDecidersByRun(ctx context.Context, runID string) ([]ListApprovalDecidersByRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listApprovalDecidersByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovalDecidersByRunRow
	for rows.Next() {
		var i ListApprovalDecidersByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.DecidedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredApprovalRequests = `-- name: ListExpiredApprovalRequests :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at, decided_by FROM approval_requests WHERE status = 'pending' AND expires_at <= ?1
`

// ListExpiredApprovalRequests accepts a cutoff timestamp and returns all pending
// requests whose expires_at is at or before that value. Callers typically pass
// time.Now() but can pass an earlier value to query historical expiry state.
func (q *Queries) ListExpiredApprovalRequests(ctx context.Context, cutoff string) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredApprovalRequests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalRequests = `-- name: ListPendingApprovalRequests :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at, decided_by FROM approval_requests WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingApprovalRequests(ctx context.Context) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovalRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalRequestStatus = `-- name: UpdateApprovalRequestStatus :execrows
UPDATE approval_requests
SET status = ?1, decided_at = ?2, note = ?3, decided_by = ?4
WHERE id = ?5 AND status = 'pending'
`

type UpdateApprovalRequestStatusParams struct {
	Status    string  `json:"status"`
	DecidedAt *string `json:"decided_at"`
	Note      *string `json:"note"`
	DecidedBy *string `json:"decided_by"`
	ID        string  `json:"id"`
}

// UpdateApprovalRequestStatus transitions a pending approval to a terminal status.
// The WHERE clause guards against double-transition: if another writer (scanner
// or agent timer) already resolved the request, rows_affected == 0 and the
// caller must treat that as "already resolved, skip downstream side-effects".
func (q *Queries) UpdateApprovalRequestStatus(ctx context.Context, arg UpdateApprovalRequestStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateApprovalRequestStatus,
		arg.Status,
		arg.DecidedAt,
		arg.Note,
		arg.DecidedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
