// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval_requests.sql

package db

import (
	"context"
)

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO approval_requests (id, run_id, tool_name, proposed_input, reasoning_summary, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6, ?7)
RETURNING id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at
`

type CreateApprovalRequestParams struct {
	ID               string `json:"id"`
	RunID            string `json:"run_id"`
	ToolName         string `json:"tool_name"`
	ProposedInput    string `json:"proposed_input"`
	ReasoningSummary string `json:"reasoning_summary"`
	ExpiresAt        string `json:"expires_at"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRowContext(ctx, createApprovalRequest,
		arg.ID,
		arg.RunID,
		arg.ToolName,
		arg.ProposedInput,
		arg.ReasoningSummary,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.ReasoningSummary,
		&i.Status,
		&i.DecidedAt,
		&i.ExpiresAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at FROM approval_requests WHERE id = ?1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id string) (ApprovalRequest, error) {
	row := q.db.QueryRowContext(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.ReasoningSummary,
		&i.Status,
		&i.DecidedAt,
		&i.ExpiresAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingApprovalRequestsByRun = `-- name: GetPendingApprovalRequestsByRun :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at FROM approval_requests
WHERE run_id = ?1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingApprovalRequestsByRun(ctx context.Context, runID string) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingApprovalRequestsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredApprovalRequests = `-- name: ListExpiredApprovalRequests :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at FROM approval_requests WHERE status = 'pending' AND expires_at <= ?1
`

// ListExpiredApprovalRequests accepts a cutoff timestamp and returns all pending
// requests whose expires_at is at or before that value. Callers typically pass
// time.Now() but can pass an earlier value to query historical expiry state.
func (q *Queries) ListExpiredApprovalRequests(ctx context.Context, cutoff string) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredApprovalRequests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalRequests = `-- name: ListPendingApprovalRequests :many
SELECT id, run_id, tool_name, proposed_input, reasoning_summary, status, decided_at, expires_at, note, created_at FROM approval_requests WHERE status = 'pending' ORDER BY created_at ASC
`

func (q *Queries) ListPendingApprovalRequests(ctx context.Context) ([]ApprovalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovalRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovalRequest
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.ReasoningSummary,
			&i.Status,
			&i.DecidedAt,
			&i.ExpiresAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalRequestStatus = `-- name: UpdateApprovalRequestStatus :exec
UPDATE approval_requests
SET status = ?1, decided_at = ?2, note = ?3
WHERE id = ?4
`

type UpdateApprovalRequestStatusParams struct {
	Status    string  `json:"status"`
	DecidedAt *string `json:"decided_at"`
	Note      *string `json:"note"`
	ID        string  `json:"id"`
}

// UpdateApprovalRequestStatus: caller is responsible for valid state transitions
// (pending -> approved / rejected / timeout). The schema CHECK constraint
// enforces enum membership but not transition ordering.
func (q *Queries) UpdateApprovalRequestStatus(ctx context.Context, arg UpdateApprovalRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateApprovalRequestStatus,
		arg.Status,
		arg.DecidedAt,
		arg.Note,
		arg.ID,
	)
	return err
}

const deleteApprovalRequestsByPolicyRuns = `-- name: DeleteApprovalRequestsByPolicyRuns :exec
DELETE FROM approval_requests WHERE run_id IN (SELECT id FROM runs WHERE policy_id = ?1)
`

func (q *Queries) DeleteApprovalRequestsByPolicyRuns(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deleteApprovalRequestsByPolicyRuns, policyID)
	return err
}
