// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback_requests.sql

package db

import (
	"context"
)

const countPendingFeedbackRequests = `-- name: CountPendingFeedbackRequests :one
SELECT COUNT(*) FROM feedback_requests WHERE status = 'pending'
`

func (q *Queries) CountPendingFeedbackRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingFeedbackRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedbackRequest = `-- name: CreateFeedbackRequest :one
INSERT INTO feedback_requests (id, run_id, tool_name, proposed_input, message, status, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6)
RETURNING id, run_id, tool_name, proposed_input, message, status, response, resolved_at, created_at
`

type CreateFeedbackRequestParams struct {
	ID            string `json:"id"`
	RunID         string `json:"run_id"`
	ToolName      string `json:"tool_name"`
	ProposedInput string `json:"proposed_input"`
	Message       string `json:"message"`
	CreatedAt     string `json:"created_at"`
}

func (q *Queries) CreateFeedbackRequest(ctx context.Context, arg CreateFeedbackRequestParams) (FeedbackRequest, error) {
	row := q.db.QueryRowContext(ctx, createFeedbackRequest,
		arg.ID,
		arg.RunID,
		arg.ToolName,
		arg.ProposedInput,
		arg.Message,
		arg.CreatedAt,
	)
	var i FeedbackRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedbackRequest = `-- name: GetFeedbackRequest :one
SELECT id, run_id, tool_name, proposed_input, message, status, response, resolved_at, created_at FROM feedback_requests WHERE id = ?1
`

func (q *Queries) GetFeedbackRequest(ctx context.Context, id string) (FeedbackRequest, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackRequest, id)
	var i FeedbackRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingFeedbackRequestsByRun = `-- name: GetPendingFeedbackRequestsByRun :many
SELECT id, run_id, tool_name, proposed_input, message, status, response, resolved_at, created_at FROM feedback_requests WHERE run_id = ?1 AND status = 'pending'
`

func (q *Queries) GetPendingFeedbackRequestsByRun(ctx context.Context, runID string) ([]FeedbackRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFeedbackRequestsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackRequest
	for rows.Next() {
		var i FeedbackRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedbackRequestStatus = `-- name: UpdateFeedbackRequestStatus :exec
UPDATE feedback_requests
SET status = ?1, response = ?2, resolved_at = ?3
WHERE id = ?4
`

type UpdateFeedbackRequestStatusParams struct {
	Status     string  `json:"status"`
	Response   *string `json:"response"`
	ResolvedAt *string `json:"resolved_at"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateFeedbackRequestStatus(ctx context.Context, arg UpdateFeedbackRequestStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedbackRequestStatus,
		arg.Status,
		arg.Response,
		arg.ResolvedAt,
		arg.ID,
	)
	return err
}
