// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback_requests.sql

package db

import (
	"context"
)

const countPendingFeedbackRequests = `-- name: CountPendingFeedbackRequests :one
SELECT COUNT(*) FROM feedback_requests WHERE status = 'pending'
`

func (q *Queries) CountPendingFeedbackRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingFeedbackRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeedbackRequest = `-- name: CreateFeedbackRequest :one
INSERT INTO feedback_requests (id, run_id, tool_name, proposed_input, message, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6, ?7)
RETURNING id, run_id, tool_name, proposed_input, message, status, response, resolved_at, expires_at, created_at, responded_by
`

type CreateFeedbackRequestParams struct {
	ID            string  `json:"id"`
	RunID         string  `json:"run_id"`
	ToolName      string  `json:"tool_name"`
	ProposedInput string  `json:"proposed_input"`
	Message       string  `json:"message"`
	ExpiresAt     *string `json:"expires_at"`
	CreatedAt     string  `json:"created_at"`
}

func (q *Queries) CreateFeedbackRequest(ctx context.Context, arg CreateFeedbackRequestParams) (FeedbackRequest, error) {
	row := q.db.QueryRowContext(ctx, createFeedbackRequest,
		arg.ID,
		arg.RunID,
		arg.ToolName,
		arg.ProposedInput,
		arg.Message,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i FeedbackRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedBy,
	)
	return i, err
}

const getFeedbackRequest = `-- name: GetFeedbackRequest :one
SELECT id, run_id, tool_name, proposed_input, message, status, response, resolved_at, expires_at, created_at, responded_by FROM feedback_requests WHERE id = ?1
`

func (q *Queries) GetFeedbackRequest(ctx context.Context, id string) (FeedbackRequest, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackRequest, id)
	var i FeedbackRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ToolName,
		&i.ProposedInput,
		&i.Message,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedBy,
	)
	return i, err
}

const getPendingFeedbackRequestsByRun = `-- name: GetPendingFeedbackRequestsByRun :many
SELECT id, run_id, tool_name, proposed_input, message, status, response, resolved_at, expires_at, created_at, responded_by FROM feedback_requests WHERE run_id = ?1 AND status = 'pending'
`

func (q *Queries) GetPendingFeedbackRequestsByRun(ctx context.Context, runID string) ([]FeedbackRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingFeedbackRequestsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackRequest
	for rows.Next() {
		var i FeedbackRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.ResolvedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredFeedbackRequests = `-- name: ListExpiredFeedbackRequests :many
SELECT id, run_id, tool_name, proposed_input, message, status, response, resolved_at, expires_at, created_at, responded_by FROM feedback_requests WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at <= ?1
`

// ListExpiredFeedbackRequests returns all pending feedback requests whose
// expires_at is at or before the cutoff. Only rows with a non-NULL expires_at
// are candidates (old rows without timeout are excluded).
func (q *Queries) ListExpiredFeedbackRequests(ctx context.Context, cutoff *string) ([]FeedbackRequest, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredFeedbackRequests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackRequest
	for rows.Next() {
		var i FeedbackRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ToolName,
			&i.ProposedInput,
			&i.Message,
			&i.Status,
			&i.Response,
			&i.ResolvedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackRespondersByRun = `-- name: ListFeedbackRespondersByRun :many
SELECT fr.id, fr.status, fr.resolved_at, fr.responded_by, u.username AS responded_by_username
FROM feedback_requests fr
LEFT JOIN users u ON u.id = fr.responded_by
WHERE fr.run_id = ?1
ORDER BY fr.created_at ASC
`

type ListFeedbackRespondersByRunRow struct {
	ID                  string  `json:"id"`
	Status              string  `json:"status"`
	ResolvedAt          *string `json:"resolved_at"`
	RespondedBy         *string `json:"responded_by"`
	RespondedByUsername *string `json:"responded_by_username"`
}

// ListFeedbackRespondersByRun mirrors ListApprovalDecidersByRun for feedback.
func (q *Queries) ListFeedbackRespondersByRun(ctx context.Context, runID string) ([]ListFeedbackRespondersByRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbackRespondersByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedbackRespondersByRunRow
	for rows.Next() {
		var i ListFeedbackRespondersByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.ResolvedAt,
			&i.RespondedBy,
			&i.RespondedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeedbackRequestStatus = `-- name: UpdateFeedbackRequestStatus :execrows
UPDATE feedback_requests
SET status = ?1, response = ?2, resolved_at = ?3, responded_by = ?4
WHERE id = ?5 AND status = 'pending'
`

type UpdateFeedbackRequestStatusParams struct {
	Status      string  `json:"status"`
	Response    *string `json:"response"`
	ResolvedAt  *string `json:"resolved_at"`
	RespondedBy *string `json:"responded_by"`
	ID          string  `json:"id"`
}

// UpdateFeedbackRequestStatus transitions a pending feedback request to a terminal
// status. The WHERE clause guards against double-transition: rows_affected == 0
// means another writer already resolved the request.
func (q *Queries) UpdateFeedbackRequestStatus(ctx context.Context, arg UpdateFeedbackRequestStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFeedbackRequestStatus,
		arg.Status,
		arg.Response,
		arg.ResolvedAt,
		arg.RespondedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
