// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_tools.sql

package db

import (
	"context"
)

const deleteMCPToolByServerAndName = `-- name: DeleteMCPToolByServerAndName :exec
DELETE FROM mcp_tools WHERE server_id = ?1 AND name = ?2
`

type DeleteMCPToolByServerAndNameParams struct {
	ServerID string `json:"server_id"`
	Name     string `json:"name"`
}

func (q *Queries) DeleteMCPToolByServerAndName(ctx context.Context, arg DeleteMCPToolByServerAndNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPToolByServerAndName, arg.ServerID, arg.Name)
	return err
}

const deleteMCPToolsByServer = `-- name: DeleteMCPToolsByServer :exec
DELETE FROM mcp_tools WHERE server_id = ?1
`

func (q *Queries) DeleteMCPToolsByServer(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPToolsByServer, serverID)
	return err
}

const getMCPTool = `-- name: GetMCPTool :one
SELECT id, server_id, name, description, input_schema, capability_role, created_at FROM mcp_tools WHERE id = ?1
`

func (q *Queries) GetMCPTool(ctx context.Context, id string) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, getMCPTool, id)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CapabilityRole,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPToolByServerAndName = `-- name: GetMCPToolByServerAndName :one
SELECT t.id, t.server_id, t.name, t.description, t.input_schema, t.capability_role, t.created_at
FROM mcp_tools t
JOIN mcp_servers s ON t.server_id = s.id
WHERE s.name = ?1 AND t.name = ?2
`

type GetMCPToolByServerAndNameParams struct {
	ServerName string `json:"server_name"`
	ToolName   string `json:"tool_name"`
}

func (q *Queries) GetMCPToolByServerAndName(ctx context.Context, arg GetMCPToolByServerAndNameParams) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, getMCPToolByServerAndName, arg.ServerName, arg.ToolName)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CapabilityRole,
		&i.CreatedAt,
	)
	return i, err
}

const listMCPToolsByServer = `-- name: ListMCPToolsByServer :many
SELECT id, server_id, name, description, input_schema, capability_role, created_at FROM mcp_tools WHERE server_id = ?1 ORDER BY name ASC
`

func (q *Queries) ListMCPToolsByServer(ctx context.Context, serverID string) ([]McpTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolsByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.CapabilityRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPToolCapabilityRole = `-- name: UpdateMCPToolCapabilityRole :exec
UPDATE mcp_tools SET capability_role = ?1 WHERE id = ?2
`

type UpdateMCPToolCapabilityRoleParams struct {
	CapabilityRole string `json:"capability_role"`
	ID             string `json:"id"`
}

func (q *Queries) UpdateMCPToolCapabilityRole(ctx context.Context, arg UpdateMCPToolCapabilityRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPToolCapabilityRole, arg.CapabilityRole, arg.ID)
	return err
}

const upsertMCPTool = `-- name: UpsertMCPTool :one
INSERT INTO mcp_tools (id, server_id, name, description, input_schema, capability_role, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (server_id, name) DO UPDATE SET
    description     = excluded.description,
    input_schema    = excluded.input_schema,
    capability_role = excluded.capability_role
RETURNING id, server_id, name, description, input_schema, capability_role, created_at
`

type UpsertMCPToolParams struct {
	ID             string `json:"id"`
	ServerID       string `json:"server_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	InputSchema    string `json:"input_schema"`
	CapabilityRole string `json:"capability_role"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) UpsertMCPTool(ctx context.Context, arg UpsertMCPToolParams) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPTool,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Description,
		arg.InputSchema,
		arg.CapabilityRole,
		arg.CreatedAt,
	)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CapabilityRole,
		&i.CreatedAt,
	)
	return i, err
}
