// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_tools.sql

package db

import (
	"context"
)

const deleteMCPToolsByServer = `-- name: DeleteMCPToolsByServer :exec
DELETE FROM mcp_tools WHERE server_id = ?
`

func (q *Queries) DeleteMCPToolsByServer(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPToolsByServer, serverID)
	return err
}

const getMCPToolByServerAndName = `-- name: GetMCPToolByServerAndName :one
SELECT t.id, t.server_id, t.name, t.description, t.input_schema, t.capability_role, t.created_at
FROM mcp_tools t
JOIN mcp_servers s ON t.server_id = s.id
WHERE s.name = ? AND t.name = ?
`

type GetMCPToolByServerAndNameParams struct {
	Name   string `json:"name"`
	Name_2 string `json:"name_2"`
}

func (q *Queries) GetMCPToolByServerAndName(ctx context.Context, arg GetMCPToolByServerAndNameParams) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, getMCPToolByServerAndName, arg.Name, arg.Name_2)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CapabilityRole,
		&i.CreatedAt,
	)
	return i, err
}

const listMCPToolsByServer = `-- name: ListMCPToolsByServer :many
SELECT id, server_id, name, description, input_schema, capability_role, created_at FROM mcp_tools WHERE server_id = ? ORDER BY name ASC
`

func (q *Queries) ListMCPToolsByServer(ctx context.Context, serverID string) ([]McpTool, error) {
	rows, err := q.db.QueryContext(ctx, listMCPToolsByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTool
	for rows.Next() {
		var i McpTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Description,
			&i.InputSchema,
			&i.CapabilityRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPTool = `-- name: UpsertMCPTool :one
INSERT INTO mcp_tools (id, server_id, name, description, input_schema, capability_role, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (server_id, name) DO UPDATE SET
    description     = excluded.description,
    input_schema    = excluded.input_schema,
    capability_role = excluded.capability_role
RETURNING id, server_id, name, description, input_schema, capability_role, created_at
`

type UpsertMCPToolParams struct {
	ID             string `json:"id"`
	ServerID       string `json:"server_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	InputSchema    string `json:"input_schema"`
	CapabilityRole string `json:"capability_role"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) UpsertMCPTool(ctx context.Context, arg UpsertMCPToolParams) (McpTool, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPTool,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Description,
		arg.InputSchema,
		arg.CapabilityRole,
		arg.CreatedAt,
	)
	var i McpTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Description,
		&i.InputSchema,
		&i.CapabilityRole,
		&i.CreatedAt,
	)
	return i, err
}
