// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_servers.sql

package db

import (
	"context"
)

const countMCPServers = `-- name: CountMCPServers :one
SELECT COUNT(*) FROM mcp_servers
`

func (q *Queries) CountMCPServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMCPServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (id, name, url, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, name, url, last_discovered_at, has_drift, created_at
`

type CreateMCPServerParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, createMCPServer,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastDiscoveredAt,
		&i.HasDrift,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers WHERE id = ?1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPServer, id)
	return err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, name, url, last_discovered_at, has_drift, created_at FROM mcp_servers WHERE id = ?1
`

func (q *Queries) GetMCPServer(ctx context.Context, id string) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastDiscoveredAt,
		&i.HasDrift,
		&i.CreatedAt,
	)
	return i, err
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT id, name, url, last_discovered_at, has_drift, created_at FROM mcp_servers ORDER BY created_at ASC
`

// ListMCPServers is ordered ASC: MCP servers are administrative objects registered
// once; insertion order is the natural stable sort for configuration lists.
func (q *Queries) ListMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.LastDiscoveredAt,
			&i.HasDrift,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPServerDrift = `-- name: UpdateMCPServerDrift :exec
UPDATE mcp_servers SET has_drift = ?1 WHERE id = ?2
`

type UpdateMCPServerDriftParams struct {
	HasDrift int64  `json:"has_drift"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMCPServerDrift(ctx context.Context, arg UpdateMCPServerDriftParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerDrift, arg.HasDrift, arg.ID)
	return err
}

const updateMCPServerLastDiscovered = `-- name: UpdateMCPServerLastDiscovered :exec
UPDATE mcp_servers SET last_discovered_at = ?1 WHERE id = ?2
`

type UpdateMCPServerLastDiscoveredParams struct {
	LastDiscoveredAt *string `json:"last_discovered_at"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateMCPServerLastDiscovered(ctx context.Context, arg UpdateMCPServerLastDiscoveredParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerLastDiscovered, arg.LastDiscoveredAt, arg.ID)
	return err
}
