// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_servers.sql

package db

import (
	"context"
	"strings"
)

const countMCPServers = `-- name: CountMCPServers :one
SELECT COUNT(*) FROM mcp_servers
`

func (q *Queries) CountMCPServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMCPServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMCPServer = `-- name: CreateMCPServer :one
INSERT INTO mcp_servers (id, name, url, created_at, auth_headers_encrypted)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, name, url, last_discovered_at, has_drift, created_at, auth_headers_encrypted, protocol_version
`

type CreateMCPServerParams struct {
	ID                   string  `json:"id"`
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	CreatedAt            string  `json:"created_at"`
	AuthHeadersEncrypted *string `json:"auth_headers_encrypted"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, createMCPServer,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.AuthHeadersEncrypted,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastDiscoveredAt,
		&i.HasDrift,
		&i.CreatedAt,
		&i.AuthHeadersEncrypted,
		&i.ProtocolVersion,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers WHERE id = ?1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPServer, id)
	return err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT id, name, url, last_discovered_at, has_drift, created_at, auth_headers_encrypted, protocol_version FROM mcp_servers WHERE id = ?1
`

func (q *Queries) GetMCPServer(ctx context.Context, id string) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, getMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastDiscoveredAt,
		&i.HasDrift,
		&i.CreatedAt,
		&i.AuthHeadersEncrypted,
		&i.ProtocolVersion,
	)
	return i, err
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT id, name, url, last_discovered_at, has_drift, created_at, auth_headers_encrypted, protocol_version FROM mcp_servers ORDER BY created_at ASC
`

// ListMCPServers is ordered ASC: MCP servers are administrative objects registered
// once; insertion order is the natural stable sort for configuration lists.
func (q *Queries) ListMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpServer
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.LastDiscoveredAt,
			&i.HasDrift,
			&i.CreatedAt,
			&i.AuthHeadersEncrypted,
			&i.ProtocolVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServersWithAuthHeaders = `-- name: ListMCPServersWithAuthHeaders :many
SELECT id, auth_headers_encrypted FROM mcp_servers
WHERE auth_headers_encrypted IS NOT NULL
ORDER BY id
`

type ListMCPServersWithAuthHeadersRow struct {
	ID                   string  `json:"id"`
	AuthHeadersEncrypted *string `json:"auth_headers_encrypted"`
}

// ListMCPServersWithAuthHeaders returns only rows that have a stored ciphertext.
// Used by rotate-key to re-encrypt all MCP auth header sets.
func (q *Queries) ListMCPServersWithAuthHeaders(ctx context.Context) ([]ListMCPServersWithAuthHeadersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServersWithAuthHeaders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPServersWithAuthHeadersRow
	for rows.Next() {
		var i ListMCPServersWithAuthHeadersRow
		if err := rows.Scan(&i.ID, &i.AuthHeadersEncrypted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers
SET name = ?1, url = ?2
WHERE id = ?3
RETURNING id, name, url, last_discovered_at, has_drift, created_at, auth_headers_encrypted, protocol_version
`

type UpdateMCPServerParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRowContext(ctx, updateMCPServer, arg.Name, arg.Url, arg.ID)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.LastDiscoveredAt,
		&i.HasDrift,
		&i.CreatedAt,
		&i.AuthHeadersEncrypted,
		&i.ProtocolVersion,
	)
	return i, err
}

const updateMCPServerAuthHeaders = `-- name: UpdateMCPServerAuthHeaders :exec
UPDATE mcp_servers SET auth_headers_encrypted = ?1 WHERE id = ?2
`

type UpdateMCPServerAuthHeadersParams struct {
	AuthHeadersEncrypted *string `json:"auth_headers_encrypted"`
	ID                   string  `json:"id"`
}

func (q *Queries) UpdateMCPServerAuthHeaders(ctx context.Context, arg UpdateMCPServerAuthHeadersParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerAuthHeaders, arg.AuthHeadersEncrypted, arg.ID)
	return err
}

const updateMCPServerDrift = `-- name: UpdateMCPServerDrift :exec
UPDATE mcp_servers SET has_drift = ?1 WHERE id = ?2
`

type UpdateMCPServerDriftParams struct {
	HasDrift int64  `json:"has_drift"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMCPServerDrift(ctx context.Context, arg UpdateMCPServerDriftParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerDrift, arg.HasDrift, arg.ID)
	return err
}

const updateMCPServerLastDiscovered = `-- name: UpdateMCPServerLastDiscovered :exec
UPDATE mcp_servers SET last_discovered_at = ?1 WHERE id = ?2
`

type UpdateMCPServerLastDiscoveredParams struct {
	LastDiscoveredAt *string `json:"last_discovered_at"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateMCPServerLastDiscovered(ctx context.Context, arg UpdateMCPServerLastDiscoveredParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerLastDiscovered, arg.LastDiscoveredAt, arg.ID)
	return err
}

const updateMCPServerProtocolVersion = `-- name: UpdateMCPServerProtocolVersion :exec
UPDATE mcp_servers SET protocol_version = ?1 WHERE id = ?2
`

type UpdateMCPServerProtocolVersionParams struct {
	ProtocolVersion *string `json:"protocol_version"`
	ID              string  `json:"id"`
}

// UpdateMCPServerProtocolVersion pins the negotiated MCP protocol version
// for a registry entry. NULL clears the pin (re-probe on next discovery).
func (q *Queries) UpdateMCPServerProtocolVersion(ctx context.Context, arg UpdateMCPServerProtocolVersionParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPServerProtocolVersion, arg.ProtocolVersion, arg.ID)
	return err
}

const updateMCPServerProtocolVersionIfNotModern = `-- name: UpdateMCPServerProtocolVersionIfNotModern :execrows
UPDATE mcp_servers
SET protocol_version = ?1
WHERE id = ?2
  AND (protocol_version IN (/*SLICE:modern_versions*/?)) IS NOT TRUE
`

type UpdateMCPServerProtocolVersionIfNotModernParams struct {
	ProtocolVersion *string   `json:"protocol_version"`
	ID              string    `json:"id"`
	ModernVersions  []*string `json:"modern_versions"`
}

// UpdateMCPServerProtocolVersionIfNotModern conditionally pins the negotiated
// protocol version, refusing the write when the row's current protocol_version
// is already one of modern_versions. The guard is evaluated by SQLite against
// the live row inside this single UPDATE, not by the caller reading the row
// first and deciding whether to write. That read-then-write shape let two
// concurrent refreshes both observe a stale (e.g. NULL) protocol_version and
// race past an in-memory guard, so whichever write landed last won even if it
// demoted a server the other goroutine had just proven modern. :execrows lets
// the caller distinguish "the pin changed" (1 row) from "an established
// modern pin blocked the write" (0 rows).
//
// The condition is written as "(x IN (...)) IS NOT TRUE" rather than
// "x NOT IN (...)" for two reasons: SQLite's three-valued logic makes IS NOT
// TRUE correctly permit the write when protocol_version IS NULL (NULL IN (..)
// is NULL, and NULL IS NOT TRUE is true) without a separate "OR ... IS NULL"
// clause; and sqlc's slice-parameter rewriter (sqlc.slice) does not recognize
// a NOT-wrapped IN clause, silently leaving the literal "sqlc.slice(...)"
// text unexpanded in the generated query.
func (q *Queries) UpdateMCPServerProtocolVersionIfNotModern(ctx context.Context, arg UpdateMCPServerProtocolVersionIfNotModernParams) (int64, error) {
	query := updateMCPServerProtocolVersionIfNotModern
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProtocolVersion)
	queryParams = append(queryParams, arg.ID)
	if len(arg.ModernVersions) > 0 {
		for _, v := range arg.ModernVersions {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:modern_versions*/?", strings.Repeat(",?", len(arg.ModernVersions))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:modern_versions*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
