// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_tasks.sql

package db

import (
	"context"
)

const createMCPTask = `-- name: CreateMCPTask :one
INSERT INTO mcp_tasks (id, run_id, server_id, task_id, kind, poll_interval_ms, server_ttl, status, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'working', ?8, ?9)
RETURNING id, run_id, server_id, task_id, kind, poll_interval_ms, server_ttl, status, result, created_at, updated_at
`

type CreateMCPTaskParams struct {
	ID             string  `json:"id"`
	RunID          string  `json:"run_id"`
	ServerID       *string `json:"server_id"`
	TaskID         string  `json:"task_id"`
	Kind           string  `json:"kind"`
	PollIntervalMs *int64  `json:"poll_interval_ms"`
	ServerTtl      *string `json:"server_ttl"`
	CreatedAt      string  `json:"created_at"`
	UpdatedAt      string  `json:"updated_at"`
}

func (q *Queries) CreateMCPTask(ctx context.Context, arg CreateMCPTaskParams) (McpTask, error) {
	row := q.db.QueryRowContext(ctx, createMCPTask,
		arg.ID,
		arg.RunID,
		arg.ServerID,
		arg.TaskID,
		arg.Kind,
		arg.PollIntervalMs,
		arg.ServerTtl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i McpTask
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ServerID,
		&i.TaskID,
		&i.Kind,
		&i.PollIntervalMs,
		&i.ServerTtl,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireMCPTask = `-- name: ExpireMCPTask :execrows
UPDATE mcp_tasks
SET status = 'expired', updated_at = ?1
WHERE id = ?2 AND status IN ('working', 'input_required')
`

type ExpireMCPTaskParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

// ExpireMCPTask marks a task expired when the server-side TTL elapses before
// the task reaches a terminal state on its own (spec sec 6.5: server TTL
// expiry is surfaced as a distinct failure, not conflated with a task the
// server itself failed).
func (q *Queries) ExpireMCPTask(ctx context.Context, arg ExpireMCPTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireMCPTask, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMCPTask = `-- name: GetMCPTask :one
SELECT id, run_id, server_id, task_id, kind, poll_interval_ms, server_ttl, status, result, created_at, updated_at FROM mcp_tasks WHERE id = ?1
`

func (q *Queries) GetMCPTask(ctx context.Context, id string) (McpTask, error) {
	row := q.db.QueryRowContext(ctx, getMCPTask, id)
	var i McpTask
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ServerID,
		&i.TaskID,
		&i.Kind,
		&i.PollIntervalMs,
		&i.ServerTtl,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResumableMCPTasks = `-- name: ListResumableMCPTasks :many
SELECT id, run_id, server_id, task_id, kind, poll_interval_ms, server_ttl, status, result, created_at, updated_at FROM mcp_tasks WHERE status IN ('working', 'input_required')
`

// ListResumableMCPTasks returns every task not yet in a terminal state so the
// host can resume polling after a restart (spec sec 13 durability claim).
func (q *Queries) ListResumableMCPTasks(ctx context.Context) ([]McpTask, error) {
	rows, err := q.db.QueryContext(ctx, listResumableMCPTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpTask
	for rows.Next() {
		var i McpTask
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ServerID,
			&i.TaskID,
			&i.Kind,
			&i.PollIntervalMs,
			&i.ServerTtl,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMCPTask = `-- name: ResolveMCPTask :execrows
UPDATE mcp_tasks
SET status = ?1, result = ?2, updated_at = ?3
WHERE id = ?4 AND status IN ('working', 'input_required')
`

type ResolveMCPTaskParams struct {
	Status    string  `json:"status"`
	Result    *string `json:"result"`
	UpdatedAt string  `json:"updated_at"`
	ID        string  `json:"id"`
}

// ResolveMCPTask transitions a non-terminal task (working or input_required)
// to a terminal status (complete, failed, or cancelled) and records its
// result. The WHERE clause guards against double-transition: rows_affected
// == 0 means another writer already resolved or expired the task.
func (q *Queries) ResolveMCPTask(ctx context.Context, arg ResolveMCPTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveMCPTask,
		arg.Status,
		arg.Result,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
