// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type ApprovalRequest struct {
	ID               string  `json:"id"`
	RunID            string  `json:"run_id"`
	ToolName         string  `json:"tool_name"`
	ProposedInput    string  `json:"proposed_input"`
	ReasoningSummary string  `json:"reasoning_summary"`
	Status           string  `json:"status"`
	DecidedAt        *string `json:"decided_at"`
	ExpiresAt        string  `json:"expires_at"`
	Note             *string `json:"note"`
	CreatedAt        string  `json:"created_at"`
}

type AudienceEntry struct {
	ID               string `json:"id"`
	AudienceID       string `json:"audience_id"`
	PluginInstanceID string `json:"plugin_instance_id"`
	Position         int64  `json:"position"`
	Notify           int64  `json:"notify"`
	Request          int64  `json:"request"`
	ConfigJson       string `json:"config_json"`
}

type FeedbackRequest struct {
	ID            string  `json:"id"`
	RunID         string  `json:"run_id"`
	ToolName      string  `json:"tool_name"`
	ProposedInput string  `json:"proposed_input"`
	Message       string  `json:"message"`
	Status        string  `json:"status"`
	Response      *string `json:"response"`
	ResolvedAt    *string `json:"resolved_at"`
	ExpiresAt     *string `json:"expires_at"`
	CreatedAt     string  `json:"created_at"`
}

type McpServer struct {
	ID                   string  `json:"id"`
	Name                 string  `json:"name"`
	Url                  string  `json:"url"`
	LastDiscoveredAt     *string `json:"last_discovered_at"`
	HasDrift             int64   `json:"has_drift"`
	CreatedAt            string  `json:"created_at"`
	AuthHeadersEncrypted *string `json:"auth_headers_encrypted"`
}

type McpTool struct {
	ID          string `json:"id"`
	ServerID    string `json:"server_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	InputSchema string `json:"input_schema"`
	CreatedAt   string `json:"created_at"`
	Enabled     int64  `json:"enabled"`
}

type ModelSetting struct {
	Provider  string `json:"provider"`
	ModelName string `json:"model_name"`
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
}

type OpenaiCompatProvider struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type Plugin struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	PluginVersion    string  `json:"plugin_version"`
	ManifestSnapshot string  `json:"manifest_snapshot"`
	TrustedPubkey    string  `json:"trusted_pubkey"`
	Status           string  `json:"status"`
	BinaryPath       *string `json:"binary_path"`
	Version          int64   `json:"version"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}

type PluginAudience struct {
	ID                   string  `json:"id"`
	Name                 string  `json:"name"`
	CreatedByUserID      *string `json:"created_by_user_id"`
	Version              int64   `json:"version"`
	CreatedAt            string  `json:"created_at"`
	UpdatedAt            string  `json:"updated_at"`
	DisableInAppFallback int64   `json:"disable_in_app_fallback"`
}

type PluginAuditEvent struct {
	ID               int64   `json:"id"`
	PluginInstanceID *string `json:"plugin_instance_id"`
	EventType        string  `json:"event_type"`
	Severity         string  `json:"severity"`
	ActorUserID      *string `json:"actor_user_id"`
	PayloadJson      string  `json:"payload_json"`
	CreatedAt        string  `json:"created_at"`
}

type PluginEventDedup struct {
	PluginInstanceID string `json:"plugin_instance_id"`
	EventKind        string `json:"event_kind"`
	EventID          string `json:"event_id"`
	CreatedAtMs      int64  `json:"created_at_ms"`
}

type PluginInstance struct {
	ID                    string   `json:"id"`
	PluginID              string   `json:"plugin_id"`
	InstanceName          string   `json:"instance_name"`
	ConfigJson            string   `json:"config_json"`
	SubscriptionScopeJson string   `json:"subscription_scope_json"`
	CredentialsEncrypted  *string  `json:"credentials_encrypted"`
	CredentialsExpiresAt  *string  `json:"credentials_expires_at"`
	HandshakeVersions     string   `json:"handshake_versions"`
	HealthState           string   `json:"health_state"`
	HealthDetail          *string  `json:"health_detail"`
	LastOauthCallbackUrl  *string  `json:"last_oauth_callback_url"`
	HostEventRatePerSec   *float64 `json:"host_event_rate_per_sec"`
	HostEventBurst        *int64   `json:"host_event_burst"`
	Version               int64    `json:"version"`
	CreatedAt             string   `json:"created_at"`
	UpdatedAt             string   `json:"updated_at"`
}

type PluginOauthNonce struct {
	Nonce      string `json:"nonce"`
	InstanceID string `json:"instance_id"`
	ExpiresAt  string `json:"expires_at"`
	CreatedAt  string `json:"created_at"`
}

type PluginPendingManifest struct {
	PluginID          string `json:"plugin_id"`
	CandidateManifest string `json:"candidate_manifest"`
	OldVersion        string `json:"old_version"`
	NewVersion        string `json:"new_version"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type PluginPendingRequest struct {
	ID               string  `json:"id"`
	PluginInstanceID string  `json:"plugin_instance_id"`
	RunID            string  `json:"run_id"`
	AudienceEntryID  *string `json:"audience_entry_id"`
	ToolName         string  `json:"tool_name"`
	Status           string  `json:"status"`
	Response         *string `json:"response"`
	ExpiresAt        *string `json:"expires_at"`
	ResolvedAt       *string `json:"resolved_at"`
	CreatedAt        string  `json:"created_at"`
}

type Policy struct {
	ID                     string  `json:"id"`
	Name                   string  `json:"name"`
	TriggerType            string  `json:"trigger_type"`
	Yaml                   string  `json:"yaml"`
	WebhookSecretEncrypted *string `json:"webhook_secret_encrypted"`
	CreatedAt              string  `json:"created_at"`
	UpdatedAt              string  `json:"updated_at"`
	PausedAt               *string `json:"paused_at"`
}

type PollState struct {
	PolicyID            string  `json:"policy_id"`
	LastPollAt          *string `json:"last_poll_at"`
	LastResultHash      *string `json:"last_result_hash"`
	ConsecutiveFailures int64   `json:"consecutive_failures"`
	NextPollAt          string  `json:"next_poll_at"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
}

type Run struct {
	ID             string  `json:"id"`
	PolicyID       string  `json:"policy_id"`
	Status         string  `json:"status"`
	TriggerType    string  `json:"trigger_type"`
	TriggerPayload string  `json:"trigger_payload"`
	StartedAt      string  `json:"started_at"`
	CompletedAt    *string `json:"completed_at"`
	TokenCost      int64   `json:"token_cost"`
	Error          *string `json:"error"`
	ThreadID       *string `json:"thread_id"`
	CreatedAt      string  `json:"created_at"`
	SystemPrompt   *string `json:"system_prompt"`
	Model          string  `json:"model"`
	Version        int64   `json:"version"`
}

type RunStep struct {
	ID         string `json:"id"`
	RunID      string `json:"run_id"`
	StepNumber int64  `json:"step_number"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	TokenCost  int64  `json:"token_cost"`
	CreatedAt  string `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
	UserAgent string `json:"user_agent"`
	IpAddress string `json:"ip_address"`
}

type SystemSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type TriggerQueue struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	Position       int64  `json:"position"`
	CreatedAt      string `json:"created_at"`
}

type User struct {
	ID            string  `json:"id"`
	Username      string  `json:"username"`
	PasswordHash  string  `json:"password_hash"`
	CreatedAt     string  `json:"created_at"`
	DeactivatedAt *string `json:"deactivated_at"`
}

type UserPreference struct {
	UserID          string `json:"user_id"`
	PreferenceKey   string `json:"preference_key"`
	PreferenceValue string `json:"preference_value"`
	UpdatedAt       string `json:"updated_at"`
}

type UserRole struct {
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}
