// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_settings.sql

package db

import (
	"context"
)

const getModelSetting = `-- name: GetModelSetting :one
SELECT provider, model_name, enabled, updated_at
FROM model_settings
WHERE provider = ? AND model_name = ?
`

type GetModelSettingParams struct {
	Provider  string `json:"provider"`
	ModelName string `json:"model_name"`
}

func (q *Queries) GetModelSetting(ctx context.Context, arg GetModelSettingParams) (ModelSetting, error) {
	row := q.db.QueryRowContext(ctx, getModelSetting, arg.Provider, arg.ModelName)
	var i ModelSetting
	err := row.Scan(
		&i.Provider,
		&i.ModelName,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const listDisabledModels = `-- name: ListDisabledModels :many
SELECT provider, model_name
FROM model_settings
WHERE enabled = 0
`

type ListDisabledModelsRow struct {
	Provider  string `json:"provider"`
	ModelName string `json:"model_name"`
}

func (q *Queries) ListDisabledModels(ctx context.Context) ([]ListDisabledModelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDisabledModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDisabledModelsRow
	for rows.Next() {
		var i ListDisabledModelsRow
		if err := rows.Scan(&i.Provider, &i.ModelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelSettings = `-- name: ListModelSettings :many
SELECT provider, model_name, enabled, updated_at
FROM model_settings
ORDER BY provider, model_name
`

func (q *Queries) ListModelSettings(ctx context.Context) ([]ModelSetting, error) {
	rows, err := q.db.QueryContext(ctx, listModelSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelSetting
	for rows.Next() {
		var i ModelSetting
		if err := rows.Scan(
			&i.Provider,
			&i.ModelName,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelSetting = `-- name: UpsertModelSetting :exec
INSERT INTO model_settings (provider, model_name, enabled, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(provider, model_name) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

type UpsertModelSettingParams struct {
	Provider  string `json:"provider"`
	ModelName string `json:"model_name"`
	Enabled   int64  `json:"enabled"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertModelSetting(ctx context.Context, arg UpsertModelSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelSetting,
		arg.Provider,
		arg.ModelName,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}
