// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type ApprovalRequest struct {
	ID               string  `json:"id"`
	RunID            string  `json:"run_id"`
	ToolName         string  `json:"tool_name"`
	ProposedInput    string  `json:"proposed_input"`
	ReasoningSummary string  `json:"reasoning_summary"`
	Status           string  `json:"status"`
	DecidedAt        *string `json:"decided_at"`
	ExpiresAt        string  `json:"expires_at"`
	Note             *string `json:"note"`
	CreatedAt        string  `json:"created_at"`
}

type FeedbackRequest struct {
	ID            string  `json:"id"`
	RunID         string  `json:"run_id"`
	ToolName      string  `json:"tool_name"`
	ProposedInput string  `json:"proposed_input"`
	Message       string  `json:"message"`
	Status        string  `json:"status"`
	Response      *string `json:"response"`
	ResolvedAt    *string `json:"resolved_at"`
	ExpiresAt     *string `json:"expires_at"`
	CreatedAt     string  `json:"created_at"`
}

type McpServer struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Url              string  `json:"url"`
	LastDiscoveredAt *string `json:"last_discovered_at"`
	HasDrift         int64   `json:"has_drift"`
	CreatedAt        string  `json:"created_at"`
}

type McpTool struct {
	ID          string `json:"id"`
	ServerID    string `json:"server_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	InputSchema string `json:"input_schema"`
	CreatedAt   string `json:"created_at"`
}

type Policy struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	TriggerType string  `json:"trigger_type"`
	Yaml        string  `json:"yaml"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	PausedAt    *string `json:"paused_at"`
}

type Run struct {
	ID             string  `json:"id"`
	PolicyID       string  `json:"policy_id"`
	Status         string  `json:"status"`
	TriggerType    string  `json:"trigger_type"`
	TriggerPayload string  `json:"trigger_payload"`
	StartedAt      string  `json:"started_at"`
	CompletedAt    *string `json:"completed_at"`
	TokenCost      int64   `json:"token_cost"`
	Error          *string `json:"error"`
	ThreadID       *string `json:"thread_id"`
	CreatedAt      string  `json:"created_at"`
	SystemPrompt   *string `json:"system_prompt"`
}

type RunStep struct {
	ID         string `json:"id"`
	RunID      string `json:"run_id"`
	StepNumber int64  `json:"step_number"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	TokenCost  int64  `json:"token_cost"`
	CreatedAt  string `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
}

type Session struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

type TriggerQueue struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	Position       int64  `json:"position"`
	CreatedAt      string `json:"created_at"`
}

type User struct {
	ID            string  `json:"id"`
	Username      string  `json:"username"`
	PasswordHash  string  `json:"password_hash"`
	CreatedAt     string  `json:"created_at"`
	DeactivatedAt *string `json:"deactivated_at"`
}

type UserRole struct {
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}
