// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type ApprovalRequest struct {
	ID               string  `json:"id"`
	RunID            string  `json:"run_id"`
	ToolName         string  `json:"tool_name"`
	ProposedInput    string  `json:"proposed_input"`
	ReasoningSummary string  `json:"reasoning_summary"`
	Status           string  `json:"status"`
	DecidedAt        *string `json:"decided_at"`
	ExpiresAt        string  `json:"expires_at"`
	Note             *string `json:"note"`
	CreatedAt        string  `json:"created_at"`
}

type McpServer struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Url              string  `json:"url"`
	LastDiscoveredAt *string `json:"last_discovered_at"`
	CreatedAt        string  `json:"created_at"`
}

type McpTool struct {
	ID             string `json:"id"`
	ServerID       string `json:"server_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	InputSchema    string `json:"input_schema"`
	CapabilityRole string `json:"capability_role"`
	CreatedAt      string `json:"created_at"`
}

type Policy struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	TriggerType string  `json:"trigger_type"`
	Yaml        string  `json:"yaml"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	PausedAt    *string `json:"paused_at"`
}

type Run struct {
	ID             string  `json:"id"`
	PolicyID       string  `json:"policy_id"`
	Status         string  `json:"status"`
	TriggerType    string  `json:"trigger_type"`
	TriggerPayload string  `json:"trigger_payload"`
	StartedAt      string  `json:"started_at"`
	CompletedAt    *string `json:"completed_at"`
	TokenCost      int64   `json:"token_cost"`
	Error          *string `json:"error"`
	ThreadID       *string `json:"thread_id"`
	CreatedAt      string  `json:"created_at"`
	SystemPrompt   *string `json:"system_prompt"`
}

type RunStep struct {
	ID         string `json:"id"`
	RunID      string `json:"run_id"`
	StepNumber int64  `json:"step_number"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	TokenCost  int64  `json:"token_cost"`
	CreatedAt  string `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
}
