// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: openai_compat_providers.sql

package db

import (
	"context"
)

const createOpenAICompatProvider = `-- name: CreateOpenAICompatProvider :one
INSERT INTO openai_compat_providers (name, base_url, api_key_encrypted, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, name, base_url, api_key_encrypted, created_at, updated_at
`

type CreateOpenAICompatProviderParams struct {
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateOpenAICompatProvider(ctx context.Context, arg CreateOpenAICompatProviderParams) (OpenaiCompatProvider, error) {
	row := q.db.QueryRowContext(ctx, createOpenAICompatProvider,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OpenaiCompatProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOpenAICompatProvider = `-- name: DeleteOpenAICompatProvider :exec
DELETE FROM openai_compat_providers WHERE id = ?1
`

func (q *Queries) DeleteOpenAICompatProvider(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOpenAICompatProvider, id)
	return err
}

const getOpenAICompatProviderByID = `-- name: GetOpenAICompatProviderByID :one
SELECT id, name, base_url, api_key_encrypted, created_at, updated_at FROM openai_compat_providers WHERE id = ?1
`

func (q *Queries) GetOpenAICompatProviderByID(ctx context.Context, id int64) (OpenaiCompatProvider, error) {
	row := q.db.QueryRowContext(ctx, getOpenAICompatProviderByID, id)
	var i OpenaiCompatProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAICompatProviderByName = `-- name: GetOpenAICompatProviderByName :one
SELECT id, name, base_url, api_key_encrypted, created_at, updated_at FROM openai_compat_providers WHERE name = ?1
`

func (q *Queries) GetOpenAICompatProviderByName(ctx context.Context, name string) (OpenaiCompatProvider, error) {
	row := q.db.QueryRowContext(ctx, getOpenAICompatProviderByName, name)
	var i OpenaiCompatProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenAICompatProviders = `-- name: ListOpenAICompatProviders :many
SELECT id, name, base_url, api_key_encrypted, created_at, updated_at FROM openai_compat_providers ORDER BY name ASC
`

func (q *Queries) ListOpenAICompatProviders(ctx context.Context) ([]OpenaiCompatProvider, error) {
	rows, err := q.db.QueryContext(ctx, listOpenAICompatProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenaiCompatProvider
	for rows.Next() {
		var i OpenaiCompatProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOpenAICompatProvider = `-- name: UpdateOpenAICompatProvider :one
UPDATE openai_compat_providers
SET name = ?1,
    base_url = ?2,
    api_key_encrypted = ?3,
    updated_at = ?4
WHERE id = ?5
RETURNING id, name, base_url, api_key_encrypted, created_at, updated_at
`

type UpdateOpenAICompatProviderParams struct {
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	UpdatedAt       string `json:"updated_at"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateOpenAICompatProvider(ctx context.Context, arg UpdateOpenAICompatProviderParams) (OpenaiCompatProvider, error) {
	row := q.db.QueryRowContext(ctx, updateOpenAICompatProvider,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.UpdatedAt,
		arg.ID,
	)
	var i OpenaiCompatProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOpenAICompatProviderAPIKey = `-- name: UpdateOpenAICompatProviderAPIKey :exec
UPDATE openai_compat_providers
SET api_key_encrypted = ?1, updated_at = ?2
WHERE id = ?3
`

type UpdateOpenAICompatProviderAPIKeyParams struct {
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	UpdatedAt       string `json:"updated_at"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateOpenAICompatProviderAPIKey(ctx context.Context, arg UpdateOpenAICompatProviderAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateOpenAICompatProviderAPIKey, arg.ApiKeyEncrypted, arg.UpdatedAt, arg.ID)
	return err
}
