// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_containers.sql

package db

import (
	"context"
)

const createContainerGeneration = `-- name: CreateContainerGeneration :one
INSERT INTO plugin_container_generations (
    id, plugin_instance_id, generation, container_id, image_digest, config_hash,
    token_hash, status, created_at, updated_at
)
VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10
)
RETURNING id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at
`

type CreateContainerGenerationParams struct {
	ID               string  `json:"id"`
	PluginInstanceID string  `json:"plugin_instance_id"`
	Generation       int64   `json:"generation"`
	ContainerID      *string `json:"container_id"`
	ImageDigest      string  `json:"image_digest"`
	ConfigHash       string  `json:"config_hash"`
	TokenHash        string  `json:"token_hash"`
	Status           string  `json:"status"`
	CreatedAt        string  `json:"created_at"`
	UpdatedAt        string  `json:"updated_at"`
}

func (q *Queries) CreateContainerGeneration(ctx context.Context, arg CreateContainerGenerationParams) (PluginContainerGeneration, error) {
	row := q.db.QueryRowContext(ctx, createContainerGeneration,
		arg.ID,
		arg.PluginInstanceID,
		arg.Generation,
		arg.ContainerID,
		arg.ImageDigest,
		arg.ConfigHash,
		arg.TokenHash,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PluginContainerGeneration
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.Generation,
		&i.ContainerID,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.TokenHash,
		&i.TokenRevokedAt,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPluginContainer = `-- name: CreatePluginContainer :one
INSERT INTO plugin_containers (
    id, plugin_instance_id, image_ref, image_digest, config_hash, network_name,
    memory_limit_bytes, cpu_limit_millicores, desired_state, created_at, updated_at
)
VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8, ?9, ?10, ?11
)
RETURNING id, plugin_instance_id, image_ref, image_digest, config_hash, network_name, memory_limit_bytes, cpu_limit_millicores, desired_state, version, created_at, updated_at
`

type CreatePluginContainerParams struct {
	ID                 string `json:"id"`
	PluginInstanceID   string `json:"plugin_instance_id"`
	ImageRef           string `json:"image_ref"`
	ImageDigest        string `json:"image_digest"`
	ConfigHash         string `json:"config_hash"`
	NetworkName        string `json:"network_name"`
	MemoryLimitBytes   *int64 `json:"memory_limit_bytes"`
	CpuLimitMillicores *int64 `json:"cpu_limit_millicores"`
	DesiredState       string `json:"desired_state"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}

func (q *Queries) CreatePluginContainer(ctx context.Context, arg CreatePluginContainerParams) (PluginContainer, error) {
	row := q.db.QueryRowContext(ctx, createPluginContainer,
		arg.ID,
		arg.PluginInstanceID,
		arg.ImageRef,
		arg.ImageDigest,
		arg.ConfigHash,
		arg.NetworkName,
		arg.MemoryLimitBytes,
		arg.CpuLimitMillicores,
		arg.DesiredState,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PluginContainer
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.NetworkName,
		&i.MemoryLimitBytes,
		&i.CpuLimitMillicores,
		&i.DesiredState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContainerGeneration = `-- name: DeleteContainerGeneration :exec
DELETE FROM plugin_container_generations WHERE id = ?1
`

func (q *Queries) DeleteContainerGeneration(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteContainerGeneration, id)
	return err
}

const deletePluginContainer = `-- name: DeletePluginContainer :exec
DELETE FROM plugin_containers WHERE id = ?1
`

func (q *Queries) DeletePluginContainer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePluginContainer, id)
	return err
}

const getContainerGeneration = `-- name: GetContainerGeneration :one
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations WHERE id = ?1
`

func (q *Queries) GetContainerGeneration(ctx context.Context, id string) (PluginContainerGeneration, error) {
	row := q.db.QueryRowContext(ctx, getContainerGeneration, id)
	var i PluginContainerGeneration
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.Generation,
		&i.ContainerID,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.TokenHash,
		&i.TokenRevokedAt,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContainerGenerationByTokenHash = `-- name: GetContainerGenerationByTokenHash :one
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations
WHERE token_hash = ?1 AND token_revoked_at IS NULL
`

// GetContainerGenerationByTokenHash is the authentication lookup: a plugin
// presents its instance token, the host hashes it and finds the generation it
// belongs to. Revoked tokens are excluded here rather than by the caller, so
// there is no path that authenticates a revoked generation by forgetting a
// check.
func (q *Queries) GetContainerGenerationByTokenHash(ctx context.Context, tokenHash string) (PluginContainerGeneration, error) {
	row := q.db.QueryRowContext(ctx, getContainerGenerationByTokenHash, tokenHash)
	var i PluginContainerGeneration
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.Generation,
		&i.ContainerID,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.TokenHash,
		&i.TokenRevokedAt,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestContainerGeneration = `-- name: GetLatestContainerGeneration :one
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations
WHERE plugin_instance_id = ?1
ORDER BY generation DESC
LIMIT 1
`

// GetLatestContainerGeneration returns the highest-numbered generation for an
// instance, whatever its status. Rotation reads it to mint the next number, so
// it must NOT skip terminal rows: a generation number is never reused, even
// after its container is gone.
func (q *Queries) GetLatestContainerGeneration(ctx context.Context, pluginInstanceID string) (PluginContainerGeneration, error) {
	row := q.db.QueryRowContext(ctx, getLatestContainerGeneration, pluginInstanceID)
	var i PluginContainerGeneration
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.Generation,
		&i.ContainerID,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.TokenHash,
		&i.TokenRevokedAt,
		&i.Status,
		&i.StatusDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginContainer = `-- name: GetPluginContainer :one
SELECT id, plugin_instance_id, image_ref, image_digest, config_hash, network_name, memory_limit_bytes, cpu_limit_millicores, desired_state, version, created_at, updated_at FROM plugin_containers WHERE id = ?1
`

func (q *Queries) GetPluginContainer(ctx context.Context, id string) (PluginContainer, error) {
	row := q.db.QueryRowContext(ctx, getPluginContainer, id)
	var i PluginContainer
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.NetworkName,
		&i.MemoryLimitBytes,
		&i.CpuLimitMillicores,
		&i.DesiredState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginContainerByInstance = `-- name: GetPluginContainerByInstance :one
SELECT id, plugin_instance_id, image_ref, image_digest, config_hash, network_name, memory_limit_bytes, cpu_limit_millicores, desired_state, version, created_at, updated_at FROM plugin_containers WHERE plugin_instance_id = ?1
`

func (q *Queries) GetPluginContainerByInstance(ctx context.Context, pluginInstanceID string) (PluginContainer, error) {
	row := q.db.QueryRowContext(ctx, getPluginContainerByInstance, pluginInstanceID)
	var i PluginContainer
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.ImageRef,
		&i.ImageDigest,
		&i.ConfigHash,
		&i.NetworkName,
		&i.MemoryLimitBytes,
		&i.CpuLimitMillicores,
		&i.DesiredState,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContainerGenerationsByInstance = `-- name: ListContainerGenerationsByInstance :many
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations
WHERE plugin_instance_id = ?1
ORDER BY generation DESC
`

func (q *Queries) ListContainerGenerationsByInstance(ctx context.Context, pluginInstanceID string) ([]PluginContainerGeneration, error) {
	rows, err := q.db.QueryContext(ctx, listContainerGenerationsByInstance, pluginInstanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerGeneration
	for rows.Next() {
		var i PluginContainerGeneration
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.Generation,
			&i.ContainerID,
			&i.ImageDigest,
			&i.ConfigHash,
			&i.TokenHash,
			&i.TokenRevokedAt,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveContainerGenerations = `-- name: ListLiveContainerGenerations :many
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations
WHERE status IN ('pending', 'starting', 'healthy', 'active', 'draining')
ORDER BY plugin_instance_id, generation
`

// ListLiveContainerGenerations returns every generation that still owns a
// container the reconciler may have to act on -- the right side of its diff.
// Terminal generations (stopped, failed) are excluded: their containers are
// gone, so nothing about them can converge.
func (q *Queries) ListLiveContainerGenerations(ctx context.Context) ([]PluginContainerGeneration, error) {
	rows, err := q.db.QueryContext(ctx, listLiveContainerGenerations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerGeneration
	for rows.Next() {
		var i PluginContainerGeneration
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.Generation,
			&i.ContainerID,
			&i.ImageDigest,
			&i.ConfigHash,
			&i.TokenHash,
			&i.TokenRevokedAt,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginContainers = `-- name: ListPluginContainers :many
SELECT id, plugin_instance_id, image_ref, image_digest, config_hash, network_name, memory_limit_bytes, cpu_limit_millicores, desired_state, version, created_at, updated_at FROM plugin_containers ORDER BY plugin_instance_id
`

// ListPluginContainers returns every desired-state row. This is the left side
// of the reconciler's diff: the whole desired set, compared against whatever a
// label query returns from the runtime. It is deliberately unfiltered and
// unpaginated -- a homelab has tens of instances, and a partial desired set
// would make the diff wrong rather than merely slow.
func (q *Queries) ListPluginContainers(ctx context.Context) ([]PluginContainer, error) {
	rows, err := q.db.QueryContext(ctx, listPluginContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainer
	for rows.Next() {
		var i PluginContainer
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.ImageRef,
			&i.ImageDigest,
			&i.ConfigHash,
			&i.NetworkName,
			&i.MemoryLimitBytes,
			&i.CpuLimitMillicores,
			&i.DesiredState,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableGenerationTokens = `-- name: ListPurgeableGenerationTokens :many
SELECT id, plugin_instance_id, generation, container_id, image_digest, config_hash, token_hash, token_revoked_at, status, status_detail, created_at, updated_at FROM plugin_container_generations
WHERE token_revoked_at IS NOT NULL
  AND token_revoked_at < ?1
  AND token_hash NOT LIKE 'purged:%'
ORDER BY token_revoked_at
LIMIT ?2
`

type ListPurgeableGenerationTokensParams struct {
	Cutoff *string `json:"cutoff"`
	Limit  int64   `json:"limit"`
}

// ListPurgeableGenerationTokens returns generations whose instance token was
// revoked longer ago than the retention window and whose hash is still stored.
//
// The window exists because a revoked token is briefly still useful: a host RPC
// that arrived just before the revocation is correlated to its generation by
// hash, and purging on the instant of revocation would make the last few
// moments of a generation's life unattributable. After that it is only
// material, so it goes.
//
// The 'purged:%' guard makes the sweep idempotent. It matches the tombstone
// the purge writes -- token_hash is NOT NULL UNIQUE, so the hash is replaced
// by a per-row tombstone rather than cleared, and the row itself survives.
// Deleting the row instead would be worse in two ways: it would discard the
// rotation history an operator reads to answer "what has this instance run",
// and deleting the highest-numbered row would let the next rotation reuse a
// generation number that a stale container may still be labelled with.
func (q *Queries) ListPurgeableGenerationTokens(ctx context.Context, arg ListPurgeableGenerationTokensParams) ([]PluginContainerGeneration, error) {
	rows, err := q.db.QueryContext(ctx, listPurgeableGenerationTokens, arg.Cutoff, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerGeneration
	for rows.Next() {
		var i PluginContainerGeneration
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.Generation,
			&i.ContainerID,
			&i.ImageDigest,
			&i.ConfigHash,
			&i.TokenHash,
			&i.TokenRevokedAt,
			&i.Status,
			&i.StatusDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeContainerGenerationToken = `-- name: PurgeContainerGenerationToken :execrows
UPDATE plugin_container_generations
SET token_hash = ?1,
    updated_at = ?2
WHERE id = ?3
  AND token_revoked_at IS NOT NULL
  AND token_hash NOT LIKE 'purged:%'
`

type PurgeContainerGenerationTokenParams struct {
	TokenHash string `json:"token_hash"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

// PurgeContainerGenerationToken replaces a revoked generation's token hash with
// a tombstone. Guarded on the revocation being set and the hash not already
// being a tombstone, so a live generation's token can never be purged by a
// racing sweep and a repeated sweep is a no-op.
func (q *Queries) PurgeContainerGenerationToken(ctx context.Context, arg PurgeContainerGenerationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeContainerGenerationToken, arg.TokenHash, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeContainerGenerationToken = `-- name: RevokeContainerGenerationToken :execrows
UPDATE plugin_container_generations
SET token_revoked_at = ?1,
    updated_at = ?2
WHERE id = ?3 AND token_revoked_at IS NULL
`

type RevokeContainerGenerationTokenParams struct {
	TokenRevokedAt *string `json:"token_revoked_at"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
}

// RevokeContainerGenerationToken invalidates a generation's instance token.
// Guarded on token_revoked_at IS NULL so revocation is idempotent from the
// caller's perspective and the original revocation time is never overwritten
// by a later pass.
func (q *Queries) RevokeContainerGenerationToken(ctx context.Context, arg RevokeContainerGenerationTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeContainerGenerationToken, arg.TokenRevokedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setContainerGenerationContainerID = `-- name: SetContainerGenerationContainerID :execrows
UPDATE plugin_container_generations
SET container_id = ?1,
    updated_at = ?2
WHERE id = ?3 AND container_id IS NULL
`

type SetContainerGenerationContainerIDParams struct {
	ContainerID *string `json:"container_id"`
	UpdatedAt   string  `json:"updated_at"`
	ID          string  `json:"id"`
}

// SetContainerGenerationContainerID records the runtime-assigned container id
// once the container exists. Guarded on container_id IS NULL so a second
// create attempt cannot silently orphan the first container by overwriting the
// only reference to it.
func (q *Queries) SetContainerGenerationContainerID(ctx context.Context, arg SetContainerGenerationContainerIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setContainerGenerationContainerID, arg.ContainerID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateContainerGenerationStatus = `-- name: UpdateContainerGenerationStatus :execrows
UPDATE plugin_container_generations
SET status = ?1,
    status_detail = ?2,
    updated_at = ?3
WHERE id = ?4 AND status = ?5
`

type UpdateContainerGenerationStatusParams struct {
	Status         string  `json:"status"`
	StatusDetail   *string `json:"status_detail"`
	UpdatedAt      string  `json:"updated_at"`
	ID             string  `json:"id"`
	ExpectedStatus string  `json:"expected_status"`
}

// UpdateContainerGenerationStatus moves a generation through the rotation
// lifecycle. The expected-status guard makes each move a CAS: rows_affected ==
// 0 means the generation was not where the caller thought it was, which during
// a rotation means another pass already advanced it.
func (q *Queries) UpdateContainerGenerationStatus(ctx context.Context, arg UpdateContainerGenerationStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContainerGenerationStatus,
		arg.Status,
		arg.StatusDetail,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginContainerDesiredState = `-- name: UpdatePluginContainerDesiredState :execrows
UPDATE plugin_containers
SET image_ref = ?1,
    image_digest = ?2,
    config_hash = ?3,
    network_name = ?4,
    memory_limit_bytes = ?5,
    cpu_limit_millicores = ?6,
    desired_state = ?7,
    version = version + 1,
    updated_at = ?8
WHERE id = ?9 AND version = ?10
`

type UpdatePluginContainerDesiredStateParams struct {
	ImageRef           string `json:"image_ref"`
	ImageDigest        string `json:"image_digest"`
	ConfigHash         string `json:"config_hash"`
	NetworkName        string `json:"network_name"`
	MemoryLimitBytes   *int64 `json:"memory_limit_bytes"`
	CpuLimitMillicores *int64 `json:"cpu_limit_millicores"`
	DesiredState       string `json:"desired_state"`
	UpdatedAt          string `json:"updated_at"`
	ID                 string `json:"id"`
	ExpectedVersion    int64  `json:"expected_version"`
}

// UpdatePluginContainerDesiredState rewrites the desired state for one
// instance under an ADR-038 CAS guard: rows_affected == 0 means another writer
// moved the row first and this caller's read was stale. Callers must not
// assume their write won.
func (q *Queries) UpdatePluginContainerDesiredState(ctx context.Context, arg UpdatePluginContainerDesiredStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginContainerDesiredState,
		arg.ImageRef,
		arg.ImageDigest,
		arg.ConfigHash,
		arg.NetworkName,
		arg.MemoryLimitBytes,
		arg.CpuLimitMillicores,
		arg.DesiredState,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
