// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_audit_events.sql

package db

import (
	"context"
)

const insertPluginAuditEvent = `-- name: InsertPluginAuditEvent :one

INSERT INTO plugin_audit_events (
    plugin_instance_id, event_type, severity,
    actor_user_id, payload_json, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
RETURNING id, plugin_instance_id, event_type, severity, actor_user_id, payload_json, created_at
`

type InsertPluginAuditEventParams struct {
	PluginInstanceID *string `json:"plugin_instance_id"`
	EventType        string  `json:"event_type"`
	Severity         string  `json:"severity"`
	ActorUserID      *string `json:"actor_user_id"`
	PayloadJson      string  `json:"payload_json"`
	CreatedAt        string  `json:"created_at"`
}

// Plugin audit events (ADR-046).
//
// Operator-only audit trail for plugin lifecycle. Never surfaced to the LLM.
// All writes are host-internal -- plugins do not write here directly.
func (q *Queries) InsertPluginAuditEvent(ctx context.Context, arg InsertPluginAuditEventParams) (PluginAuditEvent, error) {
	row := q.db.QueryRowContext(ctx, insertPluginAuditEvent,
		arg.PluginInstanceID,
		arg.EventType,
		arg.Severity,
		arg.ActorUserID,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	var i PluginAuditEvent
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.EventType,
		&i.Severity,
		&i.ActorUserID,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const listPluginAuditEventsByInstance = `-- name: ListPluginAuditEventsByInstance :many
SELECT id, plugin_instance_id, event_type, severity, actor_user_id, payload_json, created_at FROM plugin_audit_events
WHERE plugin_instance_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListPluginAuditEventsByInstanceParams struct {
	PluginInstanceID *string `json:"plugin_instance_id"`
	Offset           int64   `json:"offset"`
	Limit            int64   `json:"limit"`
}

func (q *Queries) ListPluginAuditEventsByInstance(ctx context.Context, arg ListPluginAuditEventsByInstanceParams) ([]PluginAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPluginAuditEventsByInstance, arg.PluginInstanceID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginAuditEvent
	for rows.Next() {
		var i PluginAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.EventType,
			&i.Severity,
			&i.ActorUserID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginAuditEventsByType = `-- name: ListPluginAuditEventsByType :many
SELECT id, plugin_instance_id, event_type, severity, actor_user_id, payload_json, created_at FROM plugin_audit_events
WHERE event_type = ?1
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListPluginAuditEventsByTypeParams struct {
	EventType string `json:"event_type"`
	Offset    int64  `json:"offset"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListPluginAuditEventsByType(ctx context.Context, arg ListPluginAuditEventsByTypeParams) ([]PluginAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPluginAuditEventsByType, arg.EventType, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginAuditEvent
	for rows.Next() {
		var i PluginAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.EventType,
			&i.Severity,
			&i.ActorUserID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPluginAuditEvents = `-- name: ListRecentPluginAuditEvents :many
SELECT id, plugin_instance_id, event_type, severity, actor_user_id, payload_json, created_at FROM plugin_audit_events
WHERE (?1 = '' OR severity = ?1)
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListRecentPluginAuditEventsParams struct {
	Severity interface{} `json:"severity"`
	Offset   int64       `json:"offset"`
	Limit    int64       `json:"limit"`
}

// ListRecentPluginAuditEvents returns the global plugin-event feed for the
// admin UI. Severity filter is optional -- pass an empty string to disable.
func (q *Queries) ListRecentPluginAuditEvents(ctx context.Context, arg ListRecentPluginAuditEventsParams) ([]PluginAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPluginAuditEvents, arg.Severity, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginAuditEvent
	for rows.Next() {
		var i PluginAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.EventType,
			&i.Severity,
			&i.ActorUserID,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
