// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_audiences.sql

package db

import (
	"context"
)

const createAudienceEntry = `-- name: CreateAudienceEntry :one
INSERT INTO audience_entries (id, audience_id, plugin_instance_id, position, notify, request, config_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, audience_id, plugin_instance_id, position, notify, request, config_json
`

type CreateAudienceEntryParams struct {
	ID               string `json:"id"`
	AudienceID       string `json:"audience_id"`
	PluginInstanceID string `json:"plugin_instance_id"`
	Position         int64  `json:"position"`
	Notify           int64  `json:"notify"`
	Request          int64  `json:"request"`
	ConfigJson       string `json:"config_json"`
}

func (q *Queries) CreateAudienceEntry(ctx context.Context, arg CreateAudienceEntryParams) (AudienceEntry, error) {
	row := q.db.QueryRowContext(ctx, createAudienceEntry,
		arg.ID,
		arg.AudienceID,
		arg.PluginInstanceID,
		arg.Position,
		arg.Notify,
		arg.Request,
		arg.ConfigJson,
	)
	var i AudienceEntry
	err := row.Scan(
		&i.ID,
		&i.AudienceID,
		&i.PluginInstanceID,
		&i.Position,
		&i.Notify,
		&i.Request,
		&i.ConfigJson,
	)
	return i, err
}

const createPluginAudience = `-- name: CreatePluginAudience :one
INSERT INTO plugin_audiences (id, name, created_by_user_id, version, created_at, updated_at, disable_in_app_fallback)
VALUES (?1, ?2, ?3, 0, ?4, ?5, ?6)
RETURNING id, name, created_by_user_id, version, created_at, updated_at, disable_in_app_fallback
`

type CreatePluginAudienceParams struct {
	ID                   string  `json:"id"`
	Name                 string  `json:"name"`
	CreatedByUserID      *string `json:"created_by_user_id"`
	CreatedAt            string  `json:"created_at"`
	UpdatedAt            string  `json:"updated_at"`
	DisableInAppFallback int64   `json:"disable_in_app_fallback"`
}

func (q *Queries) CreatePluginAudience(ctx context.Context, arg CreatePluginAudienceParams) (PluginAudience, error) {
	row := q.db.QueryRowContext(ctx, createPluginAudience,
		arg.ID,
		arg.Name,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DisableInAppFallback,
	)
	var i PluginAudience
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableInAppFallback,
	)
	return i, err
}

const deleteAudienceEntry = `-- name: DeleteAudienceEntry :execrows
DELETE FROM audience_entries WHERE id = ?1
`

func (q *Queries) DeleteAudienceEntry(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAudienceEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePluginAudience = `-- name: DeletePluginAudience :execrows
DELETE FROM plugin_audiences WHERE id = ?1
`

func (q *Queries) DeletePluginAudience(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginAudience, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPluginAudienceByID = `-- name: GetPluginAudienceByID :one
SELECT id, name, created_by_user_id, version, created_at, updated_at, disable_in_app_fallback
FROM plugin_audiences WHERE id = ?1
`

func (q *Queries) GetPluginAudienceByID(ctx context.Context, id string) (PluginAudience, error) {
	row := q.db.QueryRowContext(ctx, getPluginAudienceByID, id)
	var i PluginAudience
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableInAppFallback,
	)
	return i, err
}

const getPluginAudienceByName = `-- name: GetPluginAudienceByName :one
SELECT id, name, created_by_user_id, version, created_at, updated_at, disable_in_app_fallback
FROM plugin_audiences WHERE name = ?1
`

func (q *Queries) GetPluginAudienceByName(ctx context.Context, name string) (PluginAudience, error) {
	row := q.db.QueryRowContext(ctx, getPluginAudienceByName, name)
	var i PluginAudience
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisableInAppFallback,
	)
	return i, err
}

const getPluginAudienceWithEntries = `-- name: GetPluginAudienceWithEntries :many
SELECT
    pa.id                      AS audience_id,
    pa.name                    AS audience_name,
    pa.created_by_user_id,
    pa.version                 AS audience_version,
    pa.created_at              AS audience_created_at,
    pa.updated_at              AS audience_updated_at,
    pa.disable_in_app_fallback AS disable_in_app_fallback,
    ae.id                      AS entry_id,
    ae.plugin_instance_id,
    ae.position,
    ae.notify,
    ae.request,
    ae.config_json
FROM plugin_audiences pa
LEFT JOIN audience_entries ae ON ae.audience_id = pa.id
WHERE pa.id = ?1
ORDER BY ae.position
`

type GetPluginAudienceWithEntriesRow struct {
	AudienceID           string  `json:"audience_id"`
	AudienceName         string  `json:"audience_name"`
	CreatedByUserID      *string `json:"created_by_user_id"`
	AudienceVersion      int64   `json:"audience_version"`
	AudienceCreatedAt    string  `json:"audience_created_at"`
	AudienceUpdatedAt    string  `json:"audience_updated_at"`
	DisableInAppFallback int64   `json:"disable_in_app_fallback"`
	EntryID              *string `json:"entry_id"`
	PluginInstanceID     *string `json:"plugin_instance_id"`
	Position             *int64  `json:"position"`
	Notify               *int64  `json:"notify"`
	Request              *int64  `json:"request"`
	ConfigJson           *string `json:"config_json"`
}

// GetPluginAudienceWithEntries returns the audience row joined with all its
// entries ordered by position. An audience with zero entries returns one row
// with NULL entry columns (LEFT JOIN). Explicit column aliases avoid any
// ambiguity for sqlc.
func (q *Queries) GetPluginAudienceWithEntries(ctx context.Context, audienceID string) ([]GetPluginAudienceWithEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPluginAudienceWithEntries, audienceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPluginAudienceWithEntriesRow
	for rows.Next() {
		var i GetPluginAudienceWithEntriesRow
		if err := rows.Scan(
			&i.AudienceID,
			&i.AudienceName,
			&i.CreatedByUserID,
			&i.AudienceVersion,
			&i.AudienceCreatedAt,
			&i.AudienceUpdatedAt,
			&i.DisableInAppFallback,
			&i.EntryID,
			&i.PluginInstanceID,
			&i.Position,
			&i.Notify,
			&i.Request,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudienceEntries = `-- name: ListAudienceEntries :many
SELECT id, audience_id, plugin_instance_id, position, notify, request, config_json
FROM audience_entries WHERE audience_id = ?1 ORDER BY position
`

func (q *Queries) ListAudienceEntries(ctx context.Context, audienceID string) ([]AudienceEntry, error) {
	rows, err := q.db.QueryContext(ctx, listAudienceEntries, audienceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AudienceEntry
	for rows.Next() {
		var i AudienceEntry
		if err := rows.Scan(
			&i.ID,
			&i.AudienceID,
			&i.PluginInstanceID,
			&i.Position,
			&i.Notify,
			&i.Request,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginAudiences = `-- name: ListPluginAudiences :many
SELECT id, name, created_by_user_id, version, created_at, updated_at, disable_in_app_fallback
FROM plugin_audiences ORDER BY name
`

func (q *Queries) ListPluginAudiences(ctx context.Context) ([]PluginAudience, error) {
	rows, err := q.db.QueryContext(ctx, listPluginAudiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginAudience
	for rows.Next() {
		var i PluginAudience
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedByUserID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisableInAppFallback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderAudienceEntry = `-- name: ReorderAudienceEntry :execrows
UPDATE audience_entries SET position = ?1 WHERE id = ?2
`

type ReorderAudienceEntryParams struct {
	Position int64  `json:"position"`
	ID       string `json:"id"`
}

// ReorderAudienceEntry updates the position of a single entry. Multi-row
// reorders inside a single transaction must use a temporary sentinel position
// to avoid transient UNIQUE(audience_id, position) violations because
// modernc.org/sqlite does not support DEFERRABLE on table constraints.
func (q *Queries) ReorderAudienceEntry(ctx context.Context, arg ReorderAudienceEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reorderAudienceEntry, arg.Position, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAudienceEntry = `-- name: UpdateAudienceEntry :execrows
UPDATE audience_entries
SET notify = ?1, request = ?2, config_json = ?3
WHERE id = ?4
`

type UpdateAudienceEntryParams struct {
	Notify     int64  `json:"notify"`
	Request    int64  `json:"request"`
	ConfigJson string `json:"config_json"`
	ID         string `json:"id"`
}

// UpdateAudienceEntry updates the notify, request, and config_json fields of
// an entry. Position is not changed here; use ReorderAudienceEntry for that.
func (q *Queries) UpdateAudienceEntry(ctx context.Context, arg UpdateAudienceEntryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAudienceEntry,
		arg.Notify,
		arg.Request,
		arg.ConfigJson,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginAudience = `-- name: UpdatePluginAudience :execrows
UPDATE plugin_audiences
SET name = ?1, disable_in_app_fallback = ?2, version = version + 1, updated_at = ?3
WHERE id = ?4 AND version = ?5
`

type UpdatePluginAudienceParams struct {
	Name                 string `json:"name"`
	DisableInAppFallback int64  `json:"disable_in_app_fallback"`
	UpdatedAt            string `json:"updated_at"`
	ID                   string `json:"id"`
	ExpectedVersion      int64  `json:"expected_version"`
}

// UpdatePluginAudience edits the audience name and disable_in_app_fallback flag,
// and bumps the CAS version. rows_affected == 0 means the expected_version did
// not match (concurrent writer) -- see ADR-038.
func (q *Queries) UpdatePluginAudience(ctx context.Context, arg UpdatePluginAudienceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginAudience,
		arg.Name,
		arg.DisableInAppFallback,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
