// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_oauth_nonces.sql

package db

import (
	"context"
)

const consumePluginOAuthNonce = `-- name: ConsumePluginOAuthNonce :one
DELETE FROM plugin_oauth_nonces WHERE nonce = ?1 RETURNING instance_id, expires_at
`

type ConsumePluginOAuthNonceRow struct {
	InstanceID string `json:"instance_id"`
	ExpiresAt  string `json:"expires_at"`
}

// ConsumePluginOAuthNonce atomically deletes the nonce and returns its
// instance_id and expires_at. Returns ErrNoRows when the nonce is unknown
// or has already been consumed.
func (q *Queries) ConsumePluginOAuthNonce(ctx context.Context, nonce string) (ConsumePluginOAuthNonceRow, error) {
	row := q.db.QueryRowContext(ctx, consumePluginOAuthNonce, nonce)
	var i ConsumePluginOAuthNonceRow
	err := row.Scan(&i.InstanceID, &i.ExpiresAt)
	return i, err
}

const deletePluginOAuthNoncesByInstance = `-- name: DeletePluginOAuthNoncesByInstance :exec
DELETE FROM plugin_oauth_nonces WHERE instance_id = ?
`

// DeletePluginOAuthNoncesByInstance removes all OAuth nonce rows for a given
// instance. Called before deleting the instance row so there are no dangling
// references.
func (q *Queries) DeletePluginOAuthNoncesByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deletePluginOAuthNoncesByInstance, instanceID)
	return err
}

const insertPluginOAuthNonce = `-- name: InsertPluginOAuthNonce :exec
INSERT INTO plugin_oauth_nonces (nonce, instance_id, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertPluginOAuthNonceParams struct {
	Nonce      string `json:"nonce"`
	InstanceID string `json:"instance_id"`
	ExpiresAt  string `json:"expires_at"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertPluginOAuthNonce(ctx context.Context, arg InsertPluginOAuthNonceParams) error {
	_, err := q.db.ExecContext(ctx, insertPluginOAuthNonce,
		arg.Nonce,
		arg.InstanceID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const prunePluginOAuthNonces = `-- name: PrunePluginOAuthNonces :exec
DELETE FROM plugin_oauth_nonces WHERE expires_at < ?1
`

func (q *Queries) PrunePluginOAuthNonces(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, prunePluginOAuthNonces, cutoff)
	return err
}
