// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package db

import (
	"context"
)

const createPlugin = `-- name: CreatePlugin :one
INSERT INTO plugins (id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, 0, ?7, ?8)
RETURNING id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at
`

type CreatePluginParams struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	PluginVersion    string `json:"plugin_version"`
	ManifestSnapshot string `json:"manifest_snapshot"`
	TrustedPubkey    string `json:"trusted_pubkey"`
	Status           string `json:"status"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, createPlugin,
		arg.ID,
		arg.Name,
		arg.PluginVersion,
		arg.ManifestSnapshot,
		arg.TrustedPubkey,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PluginVersion,
		&i.ManifestSnapshot,
		&i.TrustedPubkey,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPluginInstance = `-- name: CreatePluginInstance :one
INSERT INTO plugin_instances (id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, 0, ?12, ?13)
RETURNING id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at
`

type CreatePluginInstanceParams struct {
	ID                    string  `json:"id"`
	PluginID              string  `json:"plugin_id"`
	InstanceName          string  `json:"instance_name"`
	ConfigJson            string  `json:"config_json"`
	SubscriptionScopeJson string  `json:"subscription_scope_json"`
	CredentialsEncrypted  *string `json:"credentials_encrypted"`
	CredentialsExpiresAt  *string `json:"credentials_expires_at"`
	HandshakeVersions     string  `json:"handshake_versions"`
	HealthState           string  `json:"health_state"`
	HealthDetail          *string `json:"health_detail"`
	LastOauthCallbackUrl  *string `json:"last_oauth_callback_url"`
	CreatedAt             string  `json:"created_at"`
	UpdatedAt             string  `json:"updated_at"`
}

func (q *Queries) CreatePluginInstance(ctx context.Context, arg CreatePluginInstanceParams) (PluginInstance, error) {
	row := q.db.QueryRowContext(ctx, createPluginInstance,
		arg.ID,
		arg.PluginID,
		arg.InstanceName,
		arg.ConfigJson,
		arg.SubscriptionScopeJson,
		arg.CredentialsEncrypted,
		arg.CredentialsExpiresAt,
		arg.HandshakeVersions,
		arg.HealthState,
		arg.HealthDetail,
		arg.LastOauthCallbackUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PluginInstance
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.InstanceName,
		&i.ConfigJson,
		&i.SubscriptionScopeJson,
		&i.CredentialsEncrypted,
		&i.CredentialsExpiresAt,
		&i.HandshakeVersions,
		&i.HealthState,
		&i.HealthDetail,
		&i.LastOauthCallbackUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePluginInstance = `-- name: DeletePluginInstance :execrows
DELETE FROM plugin_instances WHERE id = ?1
`

func (q *Queries) DeletePluginInstance(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePluginInstance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPluginByID = `-- name: GetPluginByID :one
SELECT id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at FROM plugins WHERE id = ?1
`

func (q *Queries) GetPluginByID(ctx context.Context, id string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPluginByID, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PluginVersion,
		&i.ManifestSnapshot,
		&i.TrustedPubkey,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginByName = `-- name: GetPluginByName :one
SELECT id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at FROM plugins WHERE name = ?1
`

func (q *Queries) GetPluginByName(ctx context.Context, name string) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPluginByName, name)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PluginVersion,
		&i.ManifestSnapshot,
		&i.TrustedPubkey,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginInstanceByGlobalName = `-- name: GetPluginInstanceByGlobalName :one
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances WHERE instance_name = ?1 LIMIT 1
`

// GetPluginInstanceByGlobalName finds the first instance with the given name
// across all plugins. Used by subscribed trigger binding to resolve the
// operator-readable source name to an instance ID.
// Note: plugin_instances UNIQUE is (plugin_id, instance_name), not global, so
// cross-plugin name collisions are silently first-wins here. Revisit when #213
// settles the instance-id pattern.
func (q *Queries) GetPluginInstanceByGlobalName(ctx context.Context, instanceName string) (PluginInstance, error) {
	row := q.db.QueryRowContext(ctx, getPluginInstanceByGlobalName, instanceName)
	var i PluginInstance
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.InstanceName,
		&i.ConfigJson,
		&i.SubscriptionScopeJson,
		&i.CredentialsEncrypted,
		&i.CredentialsExpiresAt,
		&i.HandshakeVersions,
		&i.HealthState,
		&i.HealthDetail,
		&i.LastOauthCallbackUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginInstanceByID = `-- name: GetPluginInstanceByID :one
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances WHERE id = ?1
`

func (q *Queries) GetPluginInstanceByID(ctx context.Context, id string) (PluginInstance, error) {
	row := q.db.QueryRowContext(ctx, getPluginInstanceByID, id)
	var i PluginInstance
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.InstanceName,
		&i.ConfigJson,
		&i.SubscriptionScopeJson,
		&i.CredentialsEncrypted,
		&i.CredentialsExpiresAt,
		&i.HandshakeVersions,
		&i.HealthState,
		&i.HealthDetail,
		&i.LastOauthCallbackUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPluginInstanceByName = `-- name: GetPluginInstanceByName :one
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances WHERE plugin_id = ?1 AND instance_name = ?2
`

type GetPluginInstanceByNameParams struct {
	PluginID     string `json:"plugin_id"`
	InstanceName string `json:"instance_name"`
}

func (q *Queries) GetPluginInstanceByName(ctx context.Context, arg GetPluginInstanceByNameParams) (PluginInstance, error) {
	row := q.db.QueryRowContext(ctx, getPluginInstanceByName, arg.PluginID, arg.InstanceName)
	var i PluginInstance
	err := row.Scan(
		&i.ID,
		&i.PluginID,
		&i.InstanceName,
		&i.ConfigJson,
		&i.SubscriptionScopeJson,
		&i.CredentialsEncrypted,
		&i.CredentialsExpiresAt,
		&i.HandshakeVersions,
		&i.HealthState,
		&i.HealthDetail,
		&i.LastOauthCallbackUrl,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPluginInstances = `-- name: ListPluginInstances :many
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances ORDER BY plugin_id, instance_name
`

func (q *Queries) ListPluginInstances(ctx context.Context) ([]PluginInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPluginInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginInstance
	for rows.Next() {
		var i PluginInstance
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.InstanceName,
			&i.ConfigJson,
			&i.SubscriptionScopeJson,
			&i.CredentialsEncrypted,
			&i.CredentialsExpiresAt,
			&i.HandshakeVersions,
			&i.HealthState,
			&i.HealthDetail,
			&i.LastOauthCallbackUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginInstancesByHealth = `-- name: ListPluginInstancesByHealth :many
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances WHERE health_state = ?1 ORDER BY plugin_id, instance_name
`

func (q *Queries) ListPluginInstancesByHealth(ctx context.Context, healthState string) ([]PluginInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPluginInstancesByHealth, healthState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginInstance
	for rows.Next() {
		var i PluginInstance
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.InstanceName,
			&i.ConfigJson,
			&i.SubscriptionScopeJson,
			&i.CredentialsEncrypted,
			&i.CredentialsExpiresAt,
			&i.HandshakeVersions,
			&i.HealthState,
			&i.HealthDetail,
			&i.LastOauthCallbackUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginInstancesByPlugin = `-- name: ListPluginInstancesByPlugin :many
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances WHERE plugin_id = ?1 ORDER BY instance_name
`

func (q *Queries) ListPluginInstancesByPlugin(ctx context.Context, pluginID string) ([]PluginInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPluginInstancesByPlugin, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginInstance
	for rows.Next() {
		var i PluginInstance
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.InstanceName,
			&i.ConfigJson,
			&i.SubscriptionScopeJson,
			&i.CredentialsEncrypted,
			&i.CredentialsExpiresAt,
			&i.HandshakeVersions,
			&i.HealthState,
			&i.HealthDetail,
			&i.LastOauthCallbackUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginInstancesWithExpiringCredentials = `-- name: ListPluginInstancesWithExpiringCredentials :many
SELECT id, plugin_id, instance_name, config_json, subscription_scope_json, credentials_encrypted, credentials_expires_at, handshake_versions, health_state, health_detail, last_oauth_callback_url, version, created_at, updated_at FROM plugin_instances
WHERE credentials_expires_at IS NOT NULL
  AND credentials_expires_at <= ?1
  AND health_state IN ('healthy', 'unhealthy', 'unsigned_permissive')
ORDER BY credentials_expires_at
`

// ListPluginInstancesWithExpiringCredentials returns all instances whose
// credentials expire at or before the given cutoff timestamp. Only instances
// in an operationally active health state are included; pending_* states
// cannot accept a refresh dance anyway, and signature_invalid/crashed rows
// should not trigger refresh work.
func (q *Queries) ListPluginInstancesWithExpiringCredentials(ctx context.Context, cutoff *string) ([]PluginInstance, error) {
	rows, err := q.db.QueryContext(ctx, listPluginInstancesWithExpiringCredentials, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginInstance
	for rows.Next() {
		var i PluginInstance
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.InstanceName,
			&i.ConfigJson,
			&i.SubscriptionScopeJson,
			&i.CredentialsEncrypted,
			&i.CredentialsExpiresAt,
			&i.HandshakeVersions,
			&i.HealthState,
			&i.HealthDetail,
			&i.LastOauthCallbackUrl,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at FROM plugins ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PluginVersion,
			&i.ManifestSnapshot,
			&i.TrustedPubkey,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsByStatus = `-- name: ListPluginsByStatus :many
SELECT id, name, plugin_version, manifest_snapshot, trusted_pubkey, status, version, created_at, updated_at FROM plugins WHERE status = ?1 ORDER BY name
`

func (q *Queries) ListPluginsByStatus(ctx context.Context, status string) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPluginsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PluginVersion,
			&i.ManifestSnapshot,
			&i.TrustedPubkey,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePluginInstanceConfig = `-- name: UpdatePluginInstanceConfig :execrows
UPDATE plugin_instances SET config_json = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginInstanceConfigParams struct {
	ConfigJson      string `json:"config_json"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
	ExpectedVersion int64  `json:"expected_version"`
}

// UpdatePluginInstanceConfig writes a new config_json and bumps CAS version.
func (q *Queries) UpdatePluginInstanceConfig(ctx context.Context, arg UpdatePluginInstanceConfigParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceConfig,
		arg.ConfigJson,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginInstanceCredentials = `-- name: UpdatePluginInstanceCredentials :execrows
UPDATE plugin_instances SET credentials_encrypted = ?1, credentials_expires_at = ?2, version = version + 1, updated_at = ?3
WHERE id = ?4 AND version = ?5
`

type UpdatePluginInstanceCredentialsParams struct {
	CredentialsEncrypted *string `json:"credentials_encrypted"`
	CredentialsExpiresAt *string `json:"credentials_expires_at"`
	UpdatedAt            string  `json:"updated_at"`
	ID                   string  `json:"id"`
	ExpectedVersion      int64   `json:"expected_version"`
}

// UpdatePluginInstanceCredentials writes new encrypted credentials. Used by
// the admin write-only API surface and the OAuth refresh path (#227).
func (q *Queries) UpdatePluginInstanceCredentials(ctx context.Context, arg UpdatePluginInstanceCredentialsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceCredentials,
		arg.CredentialsEncrypted,
		arg.CredentialsExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginInstanceHandshakeVersions = `-- name: UpdatePluginInstanceHandshakeVersions :execrows
UPDATE plugin_instances SET handshake_versions = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginInstanceHandshakeVersionsParams struct {
	HandshakeVersions string `json:"handshake_versions"`
	UpdatedAt         string `json:"updated_at"`
	ID                string `json:"id"`
	ExpectedVersion   int64  `json:"expected_version"`
}

func (q *Queries) UpdatePluginInstanceHandshakeVersions(ctx context.Context, arg UpdatePluginInstanceHandshakeVersionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceHandshakeVersions,
		arg.HandshakeVersions,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginInstanceHealth = `-- name: UpdatePluginInstanceHealth :execrows
UPDATE plugin_instances SET health_state = ?1, health_detail = ?2, version = version + 1, updated_at = ?3
WHERE id = ?4 AND version = ?5
`

type UpdatePluginInstanceHealthParams struct {
	HealthState     string  `json:"health_state"`
	HealthDetail    *string `json:"health_detail"`
	UpdatedAt       string  `json:"updated_at"`
	ID              string  `json:"id"`
	ExpectedVersion int64   `json:"expected_version"`
}

// UpdatePluginInstanceHealth transitions the health_state column. CAS-guarded
// per ADR-038; the existing version column carries the lock.
func (q *Queries) UpdatePluginInstanceHealth(ctx context.Context, arg UpdatePluginInstanceHealthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceHealth,
		arg.HealthState,
		arg.HealthDetail,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginInstanceOAuthCallback = `-- name: UpdatePluginInstanceOAuthCallback :execrows
UPDATE plugin_instances SET last_oauth_callback_url = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginInstanceOAuthCallbackParams struct {
	LastOauthCallbackUrl *string `json:"last_oauth_callback_url"`
	UpdatedAt            string  `json:"updated_at"`
	ID                   string  `json:"id"`
	ExpectedVersion      int64   `json:"expected_version"`
}

func (q *Queries) UpdatePluginInstanceOAuthCallback(ctx context.Context, arg UpdatePluginInstanceOAuthCallbackParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceOAuthCallback,
		arg.LastOauthCallbackUrl,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginInstanceSubscriptionScope = `-- name: UpdatePluginInstanceSubscriptionScope :execrows
UPDATE plugin_instances SET subscription_scope_json = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginInstanceSubscriptionScopeParams struct {
	SubscriptionScopeJson string `json:"subscription_scope_json"`
	UpdatedAt             string `json:"updated_at"`
	ID                    string `json:"id"`
	ExpectedVersion       int64  `json:"expected_version"`
}

// UpdatePluginInstanceSubscriptionScope writes a new subscription_scope_json
// and bumps the CAS version. Mirrors UpdatePluginInstanceConfig; ADR-038 CAS.
func (q *Queries) UpdatePluginInstanceSubscriptionScope(ctx context.Context, arg UpdatePluginInstanceSubscriptionScopeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginInstanceSubscriptionScope,
		arg.SubscriptionScopeJson,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginManifest = `-- name: UpdatePluginManifest :execrows
UPDATE plugins SET manifest_snapshot = ?1, plugin_version = ?2, status = ?3, version = version + 1, updated_at = ?4
WHERE id = ?5 AND version = ?6
`

type UpdatePluginManifestParams struct {
	ManifestSnapshot string `json:"manifest_snapshot"`
	PluginVersion    string `json:"plugin_version"`
	Status           string `json:"status"`
	UpdatedAt        string `json:"updated_at"`
	ID               string `json:"id"`
	ExpectedVersion  int64  `json:"expected_version"`
}

// UpdatePluginManifest replaces the manifest snapshot and bumps the CAS
// version. Used when an admin approves a material manifest change
// (ADR-045 sec 4). rows_affected == 0 means the expected_version did not
// match (concurrent writer) -- see ADR-038.
func (q *Queries) UpdatePluginManifest(ctx context.Context, arg UpdatePluginManifestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginManifest,
		arg.ManifestSnapshot,
		arg.PluginVersion,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginStatus = `-- name: UpdatePluginStatus :execrows
UPDATE plugins SET status = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginStatusParams struct {
	Status          string `json:"status"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
	ExpectedVersion int64  `json:"expected_version"`
}

func (q *Queries) UpdatePluginStatus(ctx context.Context, arg UpdatePluginStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePluginTrustedPubkey = `-- name: UpdatePluginTrustedPubkey :execrows
UPDATE plugins SET trusted_pubkey = ?1, version = version + 1, updated_at = ?2
WHERE id = ?3 AND version = ?4
`

type UpdatePluginTrustedPubkeyParams struct {
	TrustedPubkey   string `json:"trusted_pubkey"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
	ExpectedVersion int64  `json:"expected_version"`
}

// UpdatePluginTrustedPubkey rotates the TOFU-pinned pubkey after an admin
// accepts a new key (ADR-045 sec 2). Same CAS guard as UpdatePluginManifest.
func (q *Queries) UpdatePluginTrustedPubkey(ctx context.Context, arg UpdatePluginTrustedPubkeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginTrustedPubkey,
		arg.TrustedPubkey,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
