// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_container_images.sql

package db

import (
	"context"
)

const countContainerImageReferences = `-- name: CountContainerImageReferences :one
SELECT COUNT(*) FROM plugin_container_generations
WHERE image_digest = ?1
  AND status IN ('pending', 'starting', 'healthy', 'active', 'draining')
`

// CountContainerImageReferences counts the live generations pinned to a
// digest. The count is derived on every read rather than stored in a column:
// a hand-maintained counter drifts, and a drifted count here means either
// deleting an image a generation still runs or never reclaiming one at all.
// Terminal generations do not count -- their containers are gone.
func (q *Queries) CountContainerImageReferences(ctx context.Context, imageDigest string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContainerImageReferences, imageDigest)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteContainerImage = `-- name: DeleteContainerImage :exec
DELETE FROM plugin_container_images WHERE digest = ?1
`

func (q *Queries) DeleteContainerImage(ctx context.Context, digest string) error {
	_, err := q.db.ExecContext(ctx, deleteContainerImage, digest)
	return err
}

const getContainerImage = `-- name: GetContainerImage :one
SELECT digest, reference, plugin_id, size_bytes, loaded_at, last_used_at FROM plugin_container_images WHERE digest = ?1
`

func (q *Queries) GetContainerImage(ctx context.Context, digest string) (PluginContainerImage, error) {
	row := q.db.QueryRowContext(ctx, getContainerImage, digest)
	var i PluginContainerImage
	err := row.Scan(
		&i.Digest,
		&i.Reference,
		&i.PluginID,
		&i.SizeBytes,
		&i.LoadedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listContainerImages = `-- name: ListContainerImages :many
SELECT digest, reference, plugin_id, size_bytes, loaded_at, last_used_at FROM plugin_container_images ORDER BY loaded_at
`

func (q *Queries) ListContainerImages(ctx context.Context) ([]PluginContainerImage, error) {
	rows, err := q.db.QueryContext(ctx, listContainerImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerImage
	for rows.Next() {
		var i PluginContainerImage
		if err := rows.Scan(
			&i.Digest,
			&i.Reference,
			&i.PluginID,
			&i.SizeBytes,
			&i.LoadedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedContainerImages = `-- name: ListUnreferencedContainerImages :many
SELECT digest, reference, plugin_id, size_bytes, loaded_at, last_used_at FROM plugin_container_images
WHERE digest NOT IN (
    SELECT image_digest FROM plugin_container_generations
    WHERE status IN ('pending', 'starting', 'healthy', 'active', 'draining')
)
ORDER BY loaded_at
`

// ListUnreferencedContainerImages returns the digests GC may reclaim: images
// no live generation still runs. Ordered oldest-first so a bounded GC pass
// reclaims the stalest images before the newest.
func (q *Queries) ListUnreferencedContainerImages(ctx context.Context) ([]PluginContainerImage, error) {
	rows, err := q.db.QueryContext(ctx, listUnreferencedContainerImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerImage
	for rows.Next() {
		var i PluginContainerImage
		if err := rows.Scan(
			&i.Digest,
			&i.Reference,
			&i.PluginID,
			&i.SizeBytes,
			&i.LoadedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchContainerImage = `-- name: TouchContainerImage :execrows
UPDATE plugin_container_images SET last_used_at = ?1 WHERE digest = ?2
`

type TouchContainerImageParams struct {
	LastUsedAt *string `json:"last_used_at"`
	Digest     string  `json:"digest"`
}

func (q *Queries) TouchContainerImage(ctx context.Context, arg TouchContainerImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchContainerImage, arg.LastUsedAt, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertContainerImage = `-- name: UpsertContainerImage :one
INSERT INTO plugin_container_images (digest, reference, plugin_id, size_bytes, loaded_at, last_used_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(digest) DO UPDATE SET
    reference = excluded.reference,
    plugin_id = excluded.plugin_id,
    size_bytes = excluded.size_bytes,
    last_used_at = excluded.last_used_at
RETURNING digest, reference, plugin_id, size_bytes, loaded_at, last_used_at
`

type UpsertContainerImageParams struct {
	Digest     string  `json:"digest"`
	Reference  string  `json:"reference"`
	PluginID   *string `json:"plugin_id"`
	SizeBytes  *int64  `json:"size_bytes"`
	LoadedAt   string  `json:"loaded_at"`
	LastUsedAt *string `json:"last_used_at"`
}

// UpsertContainerImage records a loaded OCI image. Loading the same digest
// again is not an error -- a reinstall or a second instance of the same plugin
// reaches the same bytes -- so the conflict path refreshes the mutable fields
// instead of failing.
func (q *Queries) UpsertContainerImage(ctx context.Context, arg UpsertContainerImageParams) (PluginContainerImage, error) {
	row := q.db.QueryRowContext(ctx, upsertContainerImage,
		arg.Digest,
		arg.Reference,
		arg.PluginID,
		arg.SizeBytes,
		arg.LoadedAt,
		arg.LastUsedAt,
	)
	var i PluginContainerImage
	err := row.Scan(
		&i.Digest,
		&i.Reference,
		&i.PluginID,
		&i.SizeBytes,
		&i.LoadedAt,
		&i.LastUsedAt,
	)
	return i, err
}
