// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_event_dedup.sql

package db

import (
	"context"
)

const deleteEventDedup = `-- name: DeleteEventDedup :exec
DELETE FROM plugin_event_dedup
WHERE plugin_instance_id = ?1
  AND event_kind = ?2
  AND event_id = ?3
`

type DeleteEventDedupParams struct {
	PluginInstanceID string `json:"plugin_instance_id"`
	EventKind        string `json:"event_kind"`
	EventID          string `json:"event_id"`
}

// Rolls back a dedup claim recorded by RecordEventIfNovel. Used when a matched
// event failed to launch transiently, so the plugin's at-least-once redelivery
// of the same event is treated as novel again (#585). Idempotent: a DELETE that
// affects zero rows is not an error.
func (q *Queries) DeleteEventDedup(ctx context.Context, arg DeleteEventDedupParams) error {
	_, err := q.db.ExecContext(ctx, deleteEventDedup, arg.PluginInstanceID, arg.EventKind, arg.EventID)
	return err
}

const recordEventIfNovel = `-- name: RecordEventIfNovel :execrows
INSERT INTO plugin_event_dedup (plugin_instance_id, event_kind, event_id, created_at_ms)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (plugin_instance_id, event_kind, event_id) DO NOTHING
`

type RecordEventIfNovelParams struct {
	PluginInstanceID string `json:"plugin_instance_id"`
	EventKind        string `json:"event_kind"`
	EventID          string `json:"event_id"`
	CreatedAtMs      int64  `json:"created_at_ms"`
}

func (q *Queries) RecordEventIfNovel(ctx context.Context, arg RecordEventIfNovelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordEventIfNovel,
		arg.PluginInstanceID,
		arg.EventKind,
		arg.EventID,
		arg.CreatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepEventDedup = `-- name: SweepEventDedup :execrows
DELETE FROM plugin_event_dedup WHERE created_at_ms < ?1
`

func (q *Queries) SweepEventDedup(ctx context.Context, floor int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepEventDedup, floor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
