// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_container_subnets.sql

package db

import (
	"context"
)

const allocateContainerSubnet = `-- name: AllocateContainerSubnet :one
INSERT INTO plugin_container_subnets (subnet, plugin_instance_id, pool_base, slot, allocated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING subnet, plugin_instance_id, pool_base, slot, allocated_at
`

type AllocateContainerSubnetParams struct {
	Subnet           string `json:"subnet"`
	PluginInstanceID string `json:"plugin_instance_id"`
	PoolBase         string `json:"pool_base"`
	Slot             int64  `json:"slot"`
	AllocatedAt      string `json:"allocated_at"`
}

// AllocateContainerSubnet claims one slot in the base pool for an instance.
//
// This INSERT is the allocation: there is no read-then-write window to lose,
// because UNIQUE(pool_base, slot) and UNIQUE(plugin_instance_id) are what
// arbitrate. Two callers racing for the same slot cannot both commit -- the
// loser gets a constraint violation and picks the next free slot. The pool
// arithmetic that turns a slot into a CIDR stays in the allocator, not here:
// SQL is the wrong place to reason about address space.
func (q *Queries) AllocateContainerSubnet(ctx context.Context, arg AllocateContainerSubnetParams) (PluginContainerSubnet, error) {
	row := q.db.QueryRowContext(ctx, allocateContainerSubnet,
		arg.Subnet,
		arg.PluginInstanceID,
		arg.PoolBase,
		arg.Slot,
		arg.AllocatedAt,
	)
	var i PluginContainerSubnet
	err := row.Scan(
		&i.Subnet,
		&i.PluginInstanceID,
		&i.PoolBase,
		&i.Slot,
		&i.AllocatedAt,
	)
	return i, err
}

const getContainerSubnetByInstance = `-- name: GetContainerSubnetByInstance :one
SELECT subnet, plugin_instance_id, pool_base, slot, allocated_at FROM plugin_container_subnets WHERE plugin_instance_id = ?1
`

func (q *Queries) GetContainerSubnetByInstance(ctx context.Context, pluginInstanceID string) (PluginContainerSubnet, error) {
	row := q.db.QueryRowContext(ctx, getContainerSubnetByInstance, pluginInstanceID)
	var i PluginContainerSubnet
	err := row.Scan(
		&i.Subnet,
		&i.PluginInstanceID,
		&i.PoolBase,
		&i.Slot,
		&i.AllocatedAt,
	)
	return i, err
}

const listContainerSubnetSlots = `-- name: ListContainerSubnetSlots :many
SELECT slot FROM plugin_container_subnets WHERE pool_base = ?1 ORDER BY slot
`

// ListContainerSubnetSlots returns the slots already taken in one base pool,
// ascending. The allocator reads this to pick its next candidate; the INSERT
// above, not this read, is what makes the choice safe.
func (q *Queries) ListContainerSubnetSlots(ctx context.Context, poolBase string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listContainerSubnetSlots, poolBase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var slot int64
		if err := rows.Scan(&slot); err != nil {
			return nil, err
		}
		items = append(items, slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainerSubnets = `-- name: ListContainerSubnets :many
SELECT subnet, plugin_instance_id, pool_base, slot, allocated_at FROM plugin_container_subnets ORDER BY pool_base, slot
`

func (q *Queries) ListContainerSubnets(ctx context.Context) ([]PluginContainerSubnet, error) {
	rows, err := q.db.QueryContext(ctx, listContainerSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginContainerSubnet
	for rows.Next() {
		var i PluginContainerSubnet
		if err := rows.Scan(
			&i.Subnet,
			&i.PluginInstanceID,
			&i.PoolBase,
			&i.Slot,
			&i.AllocatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseContainerSubnet = `-- name: ReleaseContainerSubnet :execrows
DELETE FROM plugin_container_subnets WHERE plugin_instance_id = ?1
`

// ReleaseContainerSubnet returns an instance's slot to the pool.
// rows_affected == 0 means the instance held no allocation, which is a
// perfectly ordinary outcome on a cleanup pass that runs twice.
func (q *Queries) ReleaseContainerSubnet(ctx context.Context, pluginInstanceID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseContainerSubnet, pluginInstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
