// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_event_cursors.sql

package db

import (
	"context"
)

const getEventCursor = `-- name: GetEventCursor :one
SELECT plugin_instance_id, cursor, sequence, scope_hash, updated_at FROM plugin_event_cursors WHERE plugin_instance_id = ?1
`

func (q *Queries) GetEventCursor(ctx context.Context, pluginInstanceID string) (PluginEventCursor, error) {
	row := q.db.QueryRowContext(ctx, getEventCursor, pluginInstanceID)
	var i PluginEventCursor
	err := row.Scan(
		&i.PluginInstanceID,
		&i.Cursor,
		&i.Sequence,
		&i.ScopeHash,
		&i.UpdatedAt,
	)
	return i, err
}

const resetEventCursor = `-- name: ResetEventCursor :exec
DELETE FROM plugin_event_cursors WHERE plugin_instance_id = ?1
`

// Clears a stale-scope cursor so the next events/listen connects with no
// cursor param, paying the redelivery cost plugin_event_dedup absorbs.
func (q *Queries) ResetEventCursor(ctx context.Context, pluginInstanceID string) error {
	_, err := q.db.ExecContext(ctx, resetEventCursor, pluginInstanceID)
	return err
}

const upsertEventCursor = `-- name: UpsertEventCursor :exec
INSERT INTO plugin_event_cursors (plugin_instance_id, cursor, sequence, scope_hash, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (plugin_instance_id) DO UPDATE SET
    cursor     = excluded.cursor,
    sequence   = excluded.sequence,
    scope_hash = excluded.scope_hash,
    updated_at = excluded.updated_at
`

type UpsertEventCursorParams struct {
	PluginInstanceID string `json:"plugin_instance_id"`
	Cursor           string `json:"cursor"`
	Sequence         int64  `json:"sequence"`
	ScopeHash        string `json:"scope_hash"`
	UpdatedAt        string `json:"updated_at"`
}

func (q *Queries) UpsertEventCursor(ctx context.Context, arg UpsertEventCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventCursor,
		arg.PluginInstanceID,
		arg.Cursor,
		arg.Sequence,
		arg.ScopeHash,
		arg.UpdatedAt,
	)
	return err
}
