// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_event_dedup.sql

package db

import (
	"context"
)

const recordEventIfNovel = `-- name: RecordEventIfNovel :execrows
INSERT INTO plugin_event_dedup (plugin_instance_id, event_kind, event_id, created_at_ms)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (plugin_instance_id, event_kind, event_id) DO NOTHING
`

type RecordEventIfNovelParams struct {
	PluginInstanceID string `json:"plugin_instance_id"`
	EventKind        string `json:"event_kind"`
	EventID          string `json:"event_id"`
	CreatedAtMs      int64  `json:"created_at_ms"`
}

func (q *Queries) RecordEventIfNovel(ctx context.Context, arg RecordEventIfNovelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordEventIfNovel,
		arg.PluginInstanceID,
		arg.EventKind,
		arg.EventID,
		arg.CreatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sweepEventDedup = `-- name: SweepEventDedup :execrows
DELETE FROM plugin_event_dedup WHERE created_at_ms < ?1
`

func (q *Queries) SweepEventDedup(ctx context.Context, floor int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, sweepEventDedup, floor)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
