// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_pending_requests.sql

package db

import (
	"context"
)

const createPluginPendingRequest = `-- name: CreatePluginPendingRequest :one
INSERT INTO plugin_pending_requests (id, plugin_instance_id, run_id, audience_entry_id, tool_name, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', ?6, ?7)
RETURNING id, plugin_instance_id, run_id, audience_entry_id, tool_name, status, response, expires_at, resolved_at, created_at
`

type CreatePluginPendingRequestParams struct {
	ID               string  `json:"id"`
	PluginInstanceID string  `json:"plugin_instance_id"`
	RunID            string  `json:"run_id"`
	AudienceEntryID  *string `json:"audience_entry_id"`
	ToolName         string  `json:"tool_name"`
	ExpiresAt        *string `json:"expires_at"`
	CreatedAt        string  `json:"created_at"`
}

func (q *Queries) CreatePluginPendingRequest(ctx context.Context, arg CreatePluginPendingRequestParams) (PluginPendingRequest, error) {
	row := q.db.QueryRowContext(ctx, createPluginPendingRequest,
		arg.ID,
		arg.PluginInstanceID,
		arg.RunID,
		arg.AudienceEntryID,
		arg.ToolName,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i PluginPendingRequest
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.RunID,
		&i.AudienceEntryID,
		&i.ToolName,
		&i.Status,
		&i.Response,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingPluginRequestsByRun = `-- name: GetPendingPluginRequestsByRun :many
SELECT id, plugin_instance_id, run_id, audience_entry_id, tool_name, status, response, expires_at, resolved_at, created_at FROM plugin_pending_requests WHERE run_id = ?1 AND status = 'pending'
`

func (q *Queries) GetPendingPluginRequestsByRun(ctx context.Context, runID string) ([]PluginPendingRequest, error) {
	rows, err := q.db.QueryContext(ctx, getPendingPluginRequestsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginPendingRequest
	for rows.Next() {
		var i PluginPendingRequest
		if err := rows.Scan(
			&i.ID,
			&i.PluginInstanceID,
			&i.RunID,
			&i.AudienceEntryID,
			&i.ToolName,
			&i.Status,
			&i.Response,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPluginPendingRequest = `-- name: GetPluginPendingRequest :one
SELECT id, plugin_instance_id, run_id, audience_entry_id, tool_name, status, response, expires_at, resolved_at, created_at FROM plugin_pending_requests WHERE id = ?1
`

func (q *Queries) GetPluginPendingRequest(ctx context.Context, id string) (PluginPendingRequest, error) {
	row := q.db.QueryRowContext(ctx, getPluginPendingRequest, id)
	var i PluginPendingRequest
	err := row.Scan(
		&i.ID,
		&i.PluginInstanceID,
		&i.RunID,
		&i.AudienceEntryID,
		&i.ToolName,
		&i.Status,
		&i.Response,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAudienceIDsWithPendingRequests = `-- name: ListAudienceIDsWithPendingRequests :many
SELECT DISTINCT ae.audience_id
FROM plugin_pending_requests p
JOIN audience_entries ae ON ae.id = p.audience_entry_id
WHERE p.status = 'pending'
`

// ListAudienceIDsWithPendingRequests returns the distinct audience IDs that
// currently have at least one pending plugin request. Used for bulk
// has_in_flight_runs on the list endpoint (no N+1).
func (q *Queries) ListAudienceIDsWithPendingRequests(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAudienceIDsWithPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var audience_id string
		if err := rows.Scan(&audience_id); err != nil {
			return nil, err
		}
		items = append(items, audience_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPluginPendingRequests = `-- name: ListExpiredPluginPendingRequests :many
SELECT id, run_id, tool_name FROM plugin_pending_requests
WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at <= ?1
`

type ListExpiredPluginPendingRequestsRow struct {
	ID       string `json:"id"`
	RunID    string `json:"run_id"`
	ToolName string `json:"tool_name"`
}

// ListExpiredPluginPendingRequests returns all pending plugin requests whose
// expires_at is at or before the cutoff. Only rows with a non-NULL expires_at
// are candidates (rows without a timeout are excluded).
func (q *Queries) ListExpiredPluginPendingRequests(ctx context.Context, cutoff *string) ([]ListExpiredPluginPendingRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPluginPendingRequests, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPluginPendingRequestsRow
	for rows.Next() {
		var i ListExpiredPluginPendingRequestsRow
		if err := rows.Scan(&i.ID, &i.RunID, &i.ToolName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPluginRequestsByAudience = `-- name: ListPendingPluginRequestsByAudience :many
SELECT p.id, p.run_id, p.audience_entry_id, p.status, r.status AS run_status
FROM plugin_pending_requests p
JOIN audience_entries ae ON ae.id = p.audience_entry_id
JOIN runs r ON r.id = p.run_id
WHERE ae.audience_id = ?1 AND p.status = 'pending'
`

type ListPendingPluginRequestsByAudienceRow struct {
	ID              string  `json:"id"`
	RunID           string  `json:"run_id"`
	AudienceEntryID *string `json:"audience_entry_id"`
	Status          string  `json:"status"`
	RunStatus       string  `json:"run_status"`
}

// ListPendingPluginRequestsByAudience returns all pending requests whose
// audience_entry_id belongs to the given audience. Used by the /references
// endpoint to surface in-flight runs for a specific audience.
func (q *Queries) ListPendingPluginRequestsByAudience(ctx context.Context, audienceID string) ([]ListPendingPluginRequestsByAudienceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPluginRequestsByAudience, audienceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingPluginRequestsByAudienceRow
	for rows.Next() {
		var i ListPendingPluginRequestsByAudienceRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AudienceEntryID,
			&i.Status,
			&i.RunStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePluginPendingRequestStatus = `-- name: UpdatePluginPendingRequestStatus :execrows
UPDATE plugin_pending_requests
SET status = ?1, response = ?2, resolved_at = ?3
WHERE id = ?4 AND status = 'pending'
`

type UpdatePluginPendingRequestStatusParams struct {
	Status     string  `json:"status"`
	Response   *string `json:"response"`
	ResolvedAt *string `json:"resolved_at"`
	ID         string  `json:"id"`
}

// UpdatePluginPendingRequestStatus transitions a pending request to a terminal
// status. The WHERE clause guards against double-transition: rows_affected == 0
// means another writer already resolved the request.
func (q *Queries) UpdatePluginPendingRequestStatus(ctx context.Context, arg UpdatePluginPendingRequestStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePluginPendingRequestStatus,
		arg.Status,
		arg.Response,
		arg.ResolvedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
