// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"
)

const clearPolicyPausedAt = `-- name: ClearPolicyPausedAt :exec
UPDATE policies SET paused_at = NULL WHERE id = ?1
`

func (q *Queries) ClearPolicyPausedAt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, clearPolicyPausedAt, id)
	return err
}

const clearPolicyWebhookSecret = `-- name: ClearPolicyWebhookSecret :exec
UPDATE policies SET webhook_secret_encrypted = NULL, updated_at = ?1 WHERE id = ?2
`

type ClearPolicyWebhookSecretParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ClearPolicyWebhookSecret(ctx context.Context, arg ClearPolicyWebhookSecretParams) error {
	_, err := q.db.ExecContext(ctx, clearPolicyWebhookSecret, arg.UpdatedAt, arg.ID)
	return err
}

const countPolicies = `-- name: CountPolicies :one
SELECT COUNT(*) FROM policies
`

func (q *Queries) CountPolicies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPolicies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (id, name, trigger_type, yaml, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at
`

type CreatePolicyParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	TriggerType string `json:"trigger_type"`
	Yaml        string `json:"yaml"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy,
		arg.ID,
		arg.Name,
		arg.TriggerType,
		arg.Yaml,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.WebhookSecretEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = ?1
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePolicy, id)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at FROM policies WHERE id = ?1
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.WebhookSecretEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const getPolicyByName = `-- name: GetPolicyByName :one
SELECT id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at FROM policies WHERE name = ?1
`

func (q *Queries) GetPolicyByName(ctx context.Context, name string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicyByName, name)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.WebhookSecretEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}

const getPolicyWebhookSecret = `-- name: GetPolicyWebhookSecret :one
SELECT webhook_secret_encrypted FROM policies WHERE id = ?1
`

func (q *Queries) GetPolicyWebhookSecret(ctx context.Context, id string) (*string, error) {
	row := q.db.QueryRowContext(ctx, getPolicyWebhookSecret, id)
	var webhook_secret_encrypted *string
	err := row.Scan(&webhook_secret_encrypted)
	return webhook_secret_encrypted, err
}

const getPollActivePolicies = `-- name: GetPollActivePolicies :many
SELECT id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at FROM policies WHERE trigger_type = 'poll' AND paused_at IS NULL
`

func (q *Queries) GetPollActivePolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, getPollActivePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Yaml,
			&i.WebhookSecretEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledActivePolicies = `-- name: GetScheduledActivePolicies :many
SELECT id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at FROM policies WHERE trigger_type = 'scheduled' AND paused_at IS NULL
`

func (q *Queries) GetScheduledActivePolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledActivePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Yaml,
			&i.WebhookSecretEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at FROM policies ORDER BY created_at DESC
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Yaml,
			&i.WebhookSecretEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesWithLatestRun = `-- name: ListPoliciesWithLatestRun :many
SELECT
    p.id,
    p.name,
    p.trigger_type,
    p.yaml,
    p.created_at,
    p.updated_at,
    p.paused_at,
    r.id          AS run_id,
    r.status      AS run_status,
    r.started_at  AS run_started_at,
    r.token_cost  AS run_token_cost,
    (SELECT CAST(COALESCE(AVG(token_cost), 0) AS INTEGER)
     FROM runs WHERE policy_id = p.id) AS avg_token_cost,
    (SELECT COUNT(*) FROM runs WHERE policy_id = p.id) AS run_count
FROM policies p
LEFT JOIN runs r ON r.id = (
    SELECT id FROM runs
    WHERE policy_id = p.id
    ORDER BY created_at DESC
    LIMIT 1
)
ORDER BY p.created_at DESC
`

type ListPoliciesWithLatestRunRow struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	TriggerType  string  `json:"trigger_type"`
	Yaml         string  `json:"yaml"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	PausedAt     *string `json:"paused_at"`
	RunID        *string `json:"run_id"`
	RunStatus    *string `json:"run_status"`
	RunStartedAt *string `json:"run_started_at"`
	RunTokenCost *int64  `json:"run_token_cost"`
	AvgTokenCost int64   `json:"avg_token_cost"`
	RunCount     int64   `json:"run_count"`
}

func (q *Queries) ListPoliciesWithLatestRun(ctx context.Context) ([]ListPoliciesWithLatestRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesWithLatestRun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesWithLatestRunRow
	for rows.Next() {
		var i ListPoliciesWithLatestRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Yaml,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PausedAt,
			&i.RunID,
			&i.RunStatus,
			&i.RunStartedAt,
			&i.RunTokenCost,
			&i.AvgTokenCost,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPolicyPausedAt = `-- name: SetPolicyPausedAt :exec
UPDATE policies SET paused_at = ?1 WHERE id = ?2
`

type SetPolicyPausedAtParams struct {
	PausedAt *string `json:"paused_at"`
	ID       string  `json:"id"`
}

func (q *Queries) SetPolicyPausedAt(ctx context.Context, arg SetPolicyPausedAtParams) error {
	_, err := q.db.ExecContext(ctx, setPolicyPausedAt, arg.PausedAt, arg.ID)
	return err
}

const setPolicyWebhookSecret = `-- name: SetPolicyWebhookSecret :exec
UPDATE policies SET webhook_secret_encrypted = ?1, updated_at = ?2 WHERE id = ?3
`

type SetPolicyWebhookSecretParams struct {
	Ciphertext *string `json:"ciphertext"`
	UpdatedAt  string  `json:"updated_at"`
	ID         string  `json:"id"`
}

func (q *Queries) SetPolicyWebhookSecret(ctx context.Context, arg SetPolicyWebhookSecretParams) error {
	_, err := q.db.ExecContext(ctx, setPolicyWebhookSecret, arg.Ciphertext, arg.UpdatedAt, arg.ID)
	return err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET name = ?1, trigger_type = ?2, yaml = ?3, updated_at = ?4
WHERE id = ?5
RETURNING id, name, trigger_type, yaml, webhook_secret_encrypted, created_at, updated_at, paused_at
`

type UpdatePolicyParams struct {
	Name        string `json:"name"`
	TriggerType string `json:"trigger_type"`
	Yaml        string `json:"yaml"`
	UpdatedAt   string `json:"updated_at"`
	ID          string `json:"id"`
}

// Note: webhook_secret_encrypted is intentionally excluded from this UPDATE so
// that policy edits (name, yaml, trigger_type) do not clear the stored secret.
// To manage the secret, use SetPolicyWebhookSecret / ClearPolicyWebhookSecret.
func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, updatePolicy,
		arg.Name,
		arg.TriggerType,
		arg.Yaml,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.WebhookSecretEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PausedAt,
	)
	return i, err
}
