// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: policies.sql

package db

import (
	"context"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policies (id, name, trigger_type, yaml, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, name, trigger_type, yaml, created_at, updated_at
`

type CreatePolicyParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	TriggerType string `json:"trigger_type"`
	Yaml        string `json:"yaml"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy,
		arg.ID,
		arg.Name,
		arg.TriggerType,
		arg.Yaml,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = ?1
`

func (q *Queries) DeletePolicy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePolicy, id)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, name, trigger_type, yaml, created_at, updated_at FROM policies WHERE id = ?1
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyByName = `-- name: GetPolicyByName :one
SELECT id, name, trigger_type, yaml, created_at, updated_at FROM policies WHERE name = ?1
`

func (q *Queries) GetPolicyByName(ctx context.Context, name string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicyByName, name)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, trigger_type, yaml, created_at, updated_at FROM policies ORDER BY created_at DESC
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.Yaml,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET yaml = ?1, updated_at = ?2
WHERE id = ?3
RETURNING id, name, trigger_type, yaml, created_at, updated_at
`

type UpdatePolicyParams struct {
	Yaml      string `json:"yaml"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, updatePolicy, arg.Yaml, arg.UpdatedAt, arg.ID)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.Yaml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
