// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: poll_states.sql

package db

import (
	"context"
)

const deletePollState = `-- name: DeletePollState :exec
DELETE FROM poll_states WHERE policy_id = ?1
`

func (q *Queries) DeletePollState(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deletePollState, policyID)
	return err
}

const getPollState = `-- name: GetPollState :one
SELECT policy_id, last_poll_at, last_result_hash, consecutive_failures, next_poll_at, created_at, updated_at FROM poll_states WHERE policy_id = ?1
`

func (q *Queries) GetPollState(ctx context.Context, policyID string) (PollState, error) {
	row := q.db.QueryRowContext(ctx, getPollState, policyID)
	var i PollState
	err := row.Scan(
		&i.PolicyID,
		&i.LastPollAt,
		&i.LastResultHash,
		&i.ConsecutiveFailures,
		&i.NextPollAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPollState = `-- name: UpsertPollState :exec
INSERT INTO poll_states (policy_id, last_poll_at, last_result_hash, consecutive_failures, next_poll_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT(policy_id) DO UPDATE SET
    last_poll_at = excluded.last_poll_at,
    last_result_hash = excluded.last_result_hash,
    consecutive_failures = excluded.consecutive_failures,
    next_poll_at = excluded.next_poll_at,
    updated_at = excluded.updated_at
`

type UpsertPollStateParams struct {
	PolicyID            string  `json:"policy_id"`
	LastPollAt          *string `json:"last_poll_at"`
	LastResultHash      *string `json:"last_result_hash"`
	ConsecutiveFailures int64   `json:"consecutive_failures"`
	NextPollAt          string  `json:"next_poll_at"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
}

func (q *Queries) UpsertPollState(ctx context.Context, arg UpsertPollStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertPollState,
		arg.PolicyID,
		arg.LastPollAt,
		arg.LastResultHash,
		arg.ConsecutiveFailures,
		arg.NextPollAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
