// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_steps.sql

package db

import (
	"context"
)

const countRunSteps = `-- name: CountRunSteps :one
SELECT COUNT(*) FROM run_steps WHERE run_id = ?1
`

func (q *Queries) CountRunSteps(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunSteps, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunStep = `-- name: CreateRunStep :one
INSERT INTO run_steps (id, run_id, step_number, type, content, token_cost, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, run_id, step_number, type, content, token_cost, created_at
`

type CreateRunStepParams struct {
	ID         string `json:"id"`
	RunID      string `json:"run_id"`
	StepNumber int64  `json:"step_number"`
	Type       string `json:"type"`
	Content    string `json:"content"`
	TokenCost  int64  `json:"token_cost"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) CreateRunStep(ctx context.Context, arg CreateRunStepParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, createRunStep,
		arg.ID,
		arg.RunID,
		arg.StepNumber,
		arg.Type,
		arg.Content,
		arg.TokenCost,
		arg.CreatedAt,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepNumber,
		&i.Type,
		&i.Content,
		&i.TokenCost,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRunStep = `-- name: GetLatestRunStep :one
SELECT id, run_id, step_number, type, content, token_cost, created_at FROM run_steps WHERE run_id = ?1 ORDER BY step_number DESC LIMIT 1
`

func (q *Queries) GetLatestRunStep(ctx context.Context, runID string) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunStep, runID)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepNumber,
		&i.Type,
		&i.Content,
		&i.TokenCost,
		&i.CreatedAt,
	)
	return i, err
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT id, run_id, step_number, type, content, token_cost, created_at FROM run_steps
WHERE run_id = ?1
  AND step_number > ?2
ORDER BY step_number ASC
LIMIT ?3
`

type ListRunStepsParams struct {
	RunID string `json:"run_id"`
	After int64  `json:"after"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListRunSteps(ctx context.Context, arg ListRunStepsParams) ([]RunStep, error) {
	rows, err := q.db.QueryContext(ctx, listRunSteps, arg.RunID, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepNumber,
			&i.Type,
			&i.Content,
			&i.TokenCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
