// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"
)

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT COUNT(*) FROM runs WHERE status IN ('pending', 'running', 'waiting_for_approval')
`

func (q *Queries) CountActiveRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, policy_id, status, trigger_type, trigger_payload, started_at, created_at)
VALUES (?1, ?2, 'pending', ?3, ?4, ?5, ?6)
RETURNING id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt
`

type CreateRunParams struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	StartedAt      string `json:"started_at"`
	CreatedAt      string `json:"created_at"`
}

// CreateRun: note that started_at is recorded at pending-creation time, not at
// the running transition. Accurate run-start timing will require making
// started_at nullable and a schema migration -- tracked as a separate issue.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.PolicyID,
		arg.TriggerType,
		arg.TriggerPayload,
		arg.StartedAt,
		arg.CreatedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TokenCost,
		&i.Error,
		&i.ThreadID,
		&i.CreatedAt,
		&i.SystemPrompt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs WHERE id = ?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TokenCost,
		&i.Error,
		&i.ThreadID,
		&i.CreatedAt,
		&i.SystemPrompt,
	)
	return i, err
}

const incrementRunTokenCost = `-- name: IncrementRunTokenCost :exec
UPDATE runs SET token_cost = token_cost + ?1 WHERE id = ?2
`

type IncrementRunTokenCostParams struct {
	TokenCost int64  `json:"token_cost"`
	ID        string `json:"id"`
}

func (q *Queries) IncrementRunTokenCost(ctx context.Context, arg IncrementRunTokenCostParams) error {
	_, err := q.db.ExecContext(ctx, incrementRunTokenCost, arg.TokenCost, arg.ID)
	return err
}

const listActiveRunsByPolicy = `-- name: ListActiveRunsByPolicy :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs
WHERE policy_id = ?1
  AND status IN ('pending', 'running', 'waiting_for_approval')
ORDER BY created_at ASC
`

func (q *Queries) ListActiveRunsByPolicy(ctx context.Context, policyID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRunsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedRuns = `-- name: ListOrphanedRuns :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs WHERE status IN ('running', 'waiting_for_approval')
`

func (q *Queries) ListOrphanedRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanedRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs
WHERE (?1 IS NULL OR policy_id = ?1)
  AND (?2 IS NULL OR status = ?2)
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListRunsParams struct {
	PolicyID interface{} `json:"policy_id"`
	Status   interface{} `json:"status"`
	Offset   int64       `json:"offset"`
	Limit    int64       `json:"limit"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns,
		arg.PolicyID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByPolicy = `-- name: ListRunsByPolicy :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs WHERE policy_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByPolicy(ctx context.Context, policyID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at, system_prompt FROM runs WHERE status = ?1 ORDER BY created_at ASC
`

func (q *Queries) ListRunsByStatus(ctx context.Context, status string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTokensLast24Hours = `-- name: SumTokensLast24Hours :one
SELECT COALESCE(SUM(token_cost), 0) FROM runs WHERE created_at >= ?1
`

func (q *Queries) SumTokensLast24Hours(ctx context.Context, since string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumTokensLast24Hours, since)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateRunError = `-- name: UpdateRunError :exec
UPDATE runs SET status = ?1, error = ?2, completed_at = ?3 WHERE id = ?4
`

type UpdateRunErrorParams struct {
	Status      string  `json:"status"`
	Error       *string `json:"error"`
	CompletedAt *string `json:"completed_at"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRunError(ctx context.Context, arg UpdateRunErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateRunError,
		arg.Status,
		arg.Error,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs SET status = ?1, completed_at = ?2 WHERE id = ?3
`

type UpdateRunStatusParams struct {
	Status      string  `json:"status"`
	CompletedAt *string `json:"completed_at"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.Status, arg.CompletedAt, arg.ID)
	return err
}

const updateRunSystemPrompt = `-- name: UpdateRunSystemPrompt :exec
UPDATE runs SET system_prompt = ?1 WHERE id = ?2
`

type UpdateRunSystemPromptParams struct {
	SystemPrompt *string `json:"system_prompt"`
	ID           string  `json:"id"`
}

func (q *Queries) UpdateRunSystemPrompt(ctx context.Context, arg UpdateRunSystemPromptParams) error {
	_, err := q.db.ExecContext(ctx, updateRunSystemPrompt, arg.SystemPrompt, arg.ID)
	return err
}

const updateRunThreadID = `-- name: UpdateRunThreadID :exec
UPDATE runs SET thread_id = ?1 WHERE id = ?2
`

type UpdateRunThreadIDParams struct {
	ThreadID *string `json:"thread_id"`
	ID       string  `json:"id"`
}

// UpdateRunThreadID: populated once when the first approval notification creates
// a Slack thread (see EPIC-010). Must only be called on a run without a thread_id.
func (q *Queries) UpdateRunThreadID(ctx context.Context, arg UpdateRunThreadIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRunThreadID, arg.ThreadID, arg.ID)
	return err
}

const deleteRunsByPolicy = `-- name: DeleteRunsByPolicy :exec
DELETE FROM runs WHERE policy_id = ?1
`

func (q *Queries) DeleteRunsByPolicy(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deleteRunsByPolicy, policyID)
	return err
}
