// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, policy_id, status, trigger_type, trigger_payload, started_at, created_at)
VALUES (?1, ?2, 'pending', ?3, ?4, ?5, ?6)
RETURNING id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at
`

type CreateRunParams struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	StartedAt      string `json:"started_at"`
	CreatedAt      string `json:"created_at"`
}

// CreateRun: note that started_at is recorded at pending-creation time, not at
// the running transition. Accurate run-start timing will require making
// started_at nullable and a schema migration -- tracked as a separate issue.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.PolicyID,
		arg.TriggerType,
		arg.TriggerPayload,
		arg.StartedAt,
		arg.CreatedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TokenCost,
		&i.Error,
		&i.ThreadID,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at FROM runs WHERE id = ?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TokenCost,
		&i.Error,
		&i.ThreadID,
		&i.CreatedAt,
	)
	return i, err
}

const incrementRunTokenCost = `-- name: IncrementRunTokenCost :exec
UPDATE runs SET token_cost = token_cost + ?1 WHERE id = ?2
`

type IncrementRunTokenCostParams struct {
	TokenCost int64  `json:"token_cost"`
	ID        string `json:"id"`
}

func (q *Queries) IncrementRunTokenCost(ctx context.Context, arg IncrementRunTokenCostParams) error {
	_, err := q.db.ExecContext(ctx, incrementRunTokenCost, arg.TokenCost, arg.ID)
	return err
}

const listRunsByPolicy = `-- name: ListRunsByPolicy :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at FROM runs WHERE policy_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) ListRunsByPolicy(ctx context.Context, policyID string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByStatus = `-- name: ListRunsByStatus :many
SELECT id, policy_id, status, trigger_type, trigger_payload, started_at, completed_at, token_cost, error, thread_id, created_at FROM runs WHERE status = ?1 ORDER BY created_at ASC
`

func (q *Queries) ListRunsByStatus(ctx context.Context, status string) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Status,
			&i.TriggerType,
			&i.TriggerPayload,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TokenCost,
			&i.Error,
			&i.ThreadID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterruptedRuns = `-- name: MarkInterruptedRuns :exec
UPDATE runs
SET status = 'interrupted', completed_at = ?1
WHERE status IN ('running', 'waiting_for_approval')
`

func (q *Queries) MarkInterruptedRuns(ctx context.Context, completedAt *string) error {
	_, err := q.db.ExecContext(ctx, markInterruptedRuns, completedAt)
	return err
}

const updateRunError = `-- name: UpdateRunError :exec
UPDATE runs SET status = ?1, error = ?2, completed_at = ?3 WHERE id = ?4
`

type UpdateRunErrorParams struct {
	Status      string  `json:"status"`
	Error       *string `json:"error"`
	CompletedAt *string `json:"completed_at"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRunError(ctx context.Context, arg UpdateRunErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateRunError,
		arg.Status,
		arg.Error,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs SET status = ?1, completed_at = ?2 WHERE id = ?3
`

type UpdateRunStatusParams struct {
	Status      string  `json:"status"`
	CompletedAt *string `json:"completed_at"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.Status, arg.CompletedAt, arg.ID)
	return err
}

const updateRunThreadID = `-- name: UpdateRunThreadID :exec
UPDATE runs SET thread_id = ?1 WHERE id = ?2
`

type UpdateRunThreadIDParams struct {
	ThreadID *string `json:"thread_id"`
	ID       string  `json:"id"`
}

// UpdateRunThreadID: populated once when the first approval notification creates
// a Slack thread (see EPIC-010). Must only be called on a run without a thread_id.
func (q *Queries) UpdateRunThreadID(ctx context.Context, arg UpdateRunThreadIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRunThreadID, arg.ThreadID, arg.ID)
	return err
}
