// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"
)

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings WHERE key = ?
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSetting, key)
	return err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at FROM system_settings WHERE key = ?
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listAPIKeySystemSettings = `-- name: ListAPIKeySystemSettings :many
SELECT key, value, updated_at
FROM system_settings
WHERE key LIKE '%_api_key'
ORDER BY key
`

func (q *Queries) ListAPIKeySystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeySystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, updated_at FROM system_settings ORDER BY key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type UpsertSystemSettingParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
