// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"
)

const clearSystemSettingIfPrefix = `-- name: ClearSystemSettingIfPrefix :execrows
UPDATE system_settings
SET value = '', updated_at = ?1
WHERE key = ?2
  AND value != ''
  AND substr(value, 1, length(CAST(?3 AS TEXT))) = CAST(?3 AS TEXT)
`

type ClearSystemSettingIfPrefixParams struct {
	UpdatedAt string `json:"updated_at"`
	Key       string `json:"key"`
	Prefix    string `json:"prefix"`
}

// Blanks the value (the "unset" form SetSystemSettingIfEmpty treats as empty)
// only while it still starts with the given prefix, in one statement so a
// concurrent re-point to another value is never clobbered. substr compares
// literally, unlike LIKE, where '_' and '%' in a prefix would be wildcards.
// Returns rows affected (0 = value absent or no longer matches).
func (q *Queries) ClearSystemSettingIfPrefix(ctx context.Context, arg ClearSystemSettingIfPrefixParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearSystemSettingIfPrefix, arg.UpdatedAt, arg.Key, arg.Prefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings WHERE key = ?
`

func (q *Queries) DeleteSystemSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSetting, key)
	return err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, updated_at FROM system_settings WHERE key = ?
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listAPIKeySystemSettings = `-- name: ListAPIKeySystemSettings :many
SELECT key, value, updated_at
FROM system_settings
WHERE key LIKE '%_api_key'
ORDER BY key
`

func (q *Queries) ListAPIKeySystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeySystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT key, value, updated_at FROM system_settings ORDER BY key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSystemSettingIfEmpty = `-- name: SetSystemSettingIfEmpty :execrows
INSERT INTO system_settings (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
WHERE system_settings.value = ''
`

type SetSystemSettingIfEmptyParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

// Writes the value only when the key is absent or holds an empty string, in
// one statement so concurrent callers cannot both win. Returns rows affected
// (0 = an existing non-empty value was left alone).
func (q *Queries) SetSystemSettingIfEmpty(ctx context.Context, arg SetSystemSettingIfEmptyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSystemSettingIfEmpty, arg.Key, arg.Value, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :exec
INSERT INTO system_settings (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type UpsertSystemSettingParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
