// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tool_input_requests.sql

package db

import (
	"context"
)

const createToolInputRequest = `-- name: CreateToolInputRequest :one
INSERT INTO tool_input_requests (id, run_id, server_id, tool_name, call_args, request_state, request_payload, elicitation_kind, status, expires_at, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, 'pending', ?9, ?10)
RETURNING id, run_id, server_id, tool_name, call_args, request_state, request_payload, elicitation_kind, status, response, resolved_at, expires_at, created_at
`

type CreateToolInputRequestParams struct {
	ID              string `json:"id"`
	RunID           string `json:"run_id"`
	ServerID        string `json:"server_id"`
	ToolName        string `json:"tool_name"`
	CallArgs        string `json:"call_args"`
	RequestState    string `json:"request_state"`
	RequestPayload  string `json:"request_payload"`
	ElicitationKind string `json:"elicitation_kind"`
	ExpiresAt       string `json:"expires_at"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) CreateToolInputRequest(ctx context.Context, arg CreateToolInputRequestParams) (ToolInputRequest, error) {
	row := q.db.QueryRowContext(ctx, createToolInputRequest,
		arg.ID,
		arg.RunID,
		arg.ServerID,
		arg.ToolName,
		arg.CallArgs,
		arg.RequestState,
		arg.RequestPayload,
		arg.ElicitationKind,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ToolInputRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ServerID,
		&i.ToolName,
		&i.CallArgs,
		&i.RequestState,
		&i.RequestPayload,
		&i.ElicitationKind,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireToolInputRequest = `-- name: ExpireToolInputRequest :execrows
UPDATE tool_input_requests
SET status = 'timed_out', resolved_at = ?1
WHERE id = ?2 AND status = 'pending'
`

type ExpireToolInputRequestParams struct {
	ResolvedAt *string `json:"resolved_at"`
	ID         string  `json:"id"`
}

// ExpireToolInputRequest transitions a pending tool input request to
// timed_out when Gleipnir's policy timeout elapses before the operator
// responds (spec sec 6.3: Gleipnir's timeout is authoritative for the human leg).
func (q *Queries) ExpireToolInputRequest(ctx context.Context, arg ExpireToolInputRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireToolInputRequest, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getToolInputRequest = `-- name: GetToolInputRequest :one
SELECT id, run_id, server_id, tool_name, call_args, request_state, request_payload, elicitation_kind, status, response, resolved_at, expires_at, created_at FROM tool_input_requests WHERE id = ?1
`

func (q *Queries) GetToolInputRequest(ctx context.Context, id string) (ToolInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getToolInputRequest, id)
	var i ToolInputRequest
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ServerID,
		&i.ToolName,
		&i.CallArgs,
		&i.RequestState,
		&i.RequestPayload,
		&i.ElicitationKind,
		&i.Status,
		&i.Response,
		&i.ResolvedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listResumableToolInputRequests = `-- name: ListResumableToolInputRequests :many
SELECT id, run_id, server_id, tool_name, call_args, request_state, request_payload, elicitation_kind, status, response, resolved_at, expires_at, created_at FROM tool_input_requests WHERE status = 'pending'
`

// ListResumableToolInputRequests returns every pending tool input request so
// the host can re-arm its wait state after a restart (spec sec 13: persisted
// requestState survives restarts even though full run resurrection does not).
func (q *Queries) ListResumableToolInputRequests(ctx context.Context) ([]ToolInputRequest, error) {
	rows, err := q.db.QueryContext(ctx, listResumableToolInputRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolInputRequest
	for rows.Next() {
		var i ToolInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ServerID,
			&i.ToolName,
			&i.CallArgs,
			&i.RequestState,
			&i.RequestPayload,
			&i.ElicitationKind,
			&i.Status,
			&i.Response,
			&i.ResolvedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveToolInputRequest = `-- name: ResolveToolInputRequest :execrows
UPDATE tool_input_requests
SET status = 'resolved', response = ?1, resolved_at = ?2
WHERE id = ?3 AND status = 'pending'
`

type ResolveToolInputRequestParams struct {
	Response   *string `json:"response"`
	ResolvedAt *string `json:"resolved_at"`
	ID         string  `json:"id"`
}

// ResolveToolInputRequest transitions a pending tool input request to resolved
// once the operator has answered. The WHERE clause guards against
// double-transition: rows_affected == 0 means another writer already
// resolved or expired the request.
func (q *Queries) ResolveToolInputRequest(ctx context.Context, arg ResolveToolInputRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveToolInputRequest, arg.Response, arg.ResolvedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
