// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trigger_queue.sql

package db

import (
	"context"
)

const countQueuedTriggers = `-- name: CountQueuedTriggers :one
SELECT COUNT(*) FROM trigger_queue WHERE policy_id = ?1
`

func (q *Queries) CountQueuedTriggers(ctx context.Context, policyID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedTriggers, policyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteQueuedTriggersByPolicy = `-- name: DeleteQueuedTriggersByPolicy :exec
DELETE FROM trigger_queue WHERE policy_id = ?1
`

func (q *Queries) DeleteQueuedTriggersByPolicy(ctx context.Context, policyID string) error {
	_, err := q.db.ExecContext(ctx, deleteQueuedTriggersByPolicy, policyID)
	return err
}

const dequeueTrigger = `-- name: DequeueTrigger :one
DELETE FROM trigger_queue
WHERE id = (
    SELECT tq.id FROM trigger_queue tq
    WHERE tq.policy_id = ?1
    ORDER BY tq.position ASC
    LIMIT 1
)
RETURNING id, policy_id, trigger_type, trigger_payload, position, created_at
`

func (q *Queries) DequeueTrigger(ctx context.Context, policyID string) (TriggerQueue, error) {
	row := q.db.QueryRowContext(ctx, dequeueTrigger, policyID)
	var i TriggerQueue
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const enqueueTrigger = `-- name: EnqueueTrigger :one
INSERT INTO trigger_queue (id, policy_id, trigger_type, trigger_payload, position, created_at)
VALUES (?1, ?2, ?3, ?4,
        (SELECT COALESCE(MAX(position), -1) + 1 FROM trigger_queue WHERE policy_id = ?2),
        ?5)
RETURNING id, policy_id, trigger_type, trigger_payload, position, created_at
`

type EnqueueTriggerParams struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) EnqueueTrigger(ctx context.Context, arg EnqueueTriggerParams) (TriggerQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueTrigger,
		arg.ID,
		arg.PolicyID,
		arg.TriggerType,
		arg.TriggerPayload,
		arg.CreatedAt,
	)
	var i TriggerQueue
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const requeueTriggerAtFront = `-- name: RequeueTriggerAtFront :one
INSERT INTO trigger_queue (id, policy_id, trigger_type, trigger_payload, position, created_at)
VALUES (?1, ?2, ?3, ?4,
        (SELECT COALESCE(MIN(position), 1) - 1 FROM trigger_queue WHERE policy_id = ?2),
        ?5)
RETURNING id, policy_id, trigger_type, trigger_payload, position, created_at
`

type RequeueTriggerAtFrontParams struct {
	ID             string `json:"id"`
	PolicyID       string `json:"policy_id"`
	TriggerType    string `json:"trigger_type"`
	TriggerPayload string `json:"trigger_payload"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) RequeueTriggerAtFront(ctx context.Context, arg RequeueTriggerAtFrontParams) (TriggerQueue, error) {
	row := q.db.QueryRowContext(ctx, requeueTriggerAtFront,
		arg.ID,
		arg.PolicyID,
		arg.TriggerType,
		arg.TriggerPayload,
		arg.CreatedAt,
	)
	var i TriggerQueue
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.TriggerType,
		&i.TriggerPayload,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
