// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"
)

const assignRole = `-- name: AssignRole :exec
INSERT OR IGNORE INTO user_roles (user_id, role, created_at)
VALUES (?1, ?2, ?3)
`

type AssignRoleParams struct {
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignRole, arg.UserID, arg.Role, arg.CreatedAt)
	return err
}

const hasRole = `-- name: HasRole :one
SELECT COUNT(*) FROM user_roles WHERE user_id = ?1 AND role = ?2
`

type HasRoleParams struct {
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) HasRole(ctx context.Context, arg HasRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasRole, arg.UserID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRolesByUser = `-- name: ListRolesByUser :many
SELECT role FROM user_roles WHERE user_id = ?1 ORDER BY role
`

func (q *Queries) ListRolesByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT ur.user_id, u.username
FROM user_roles ur
JOIN users u ON u.id = ur.user_id
WHERE ur.role = ?1
ORDER BY u.username
`

type ListUsersByRoleRow struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, role string) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByRoleRow
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllRolesForUser = `-- name: RemoveAllRolesForUser :exec
DELETE FROM user_roles WHERE user_id = ?1
`

func (q *Queries) RemoveAllRolesForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, removeAllRolesForUser, userID)
	return err
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM user_roles WHERE user_id = ?1 AND role = ?2
`

type RemoveRoleParams struct {
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) RemoveRole(ctx context.Context, arg RemoveRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeRole, arg.UserID, arg.Role)
	return err
}
