// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"
)

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences WHERE user_id = ? AND preference_key = ?
`

type DeleteUserPreferenceParams struct {
	UserID        string `json:"user_id"`
	PreferenceKey string `json:"preference_key"`
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPreference, arg.UserID, arg.PreferenceKey)
	return err
}

const listUserPreferences = `-- name: ListUserPreferences :many
SELECT user_id, preference_key, preference_value, updated_at FROM user_preferences WHERE user_id = ?
`

func (q *Queries) ListUserPreferences(ctx context.Context, userID string) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUserPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPreference
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.UserID,
			&i.PreferenceKey,
			&i.PreferenceValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPreference = `-- name: UpsertUserPreference :one
INSERT INTO user_preferences (user_id, preference_key, preference_value, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, preference_key) DO UPDATE SET preference_value = excluded.preference_value, updated_at = excluded.updated_at
RETURNING user_id, preference_key, preference_value, updated_at
`

type UpsertUserPreferenceParams struct {
	UserID          string `json:"user_id"`
	PreferenceKey   string `json:"preference_key"`
	PreferenceValue string `json:"preference_value"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreference,
		arg.UserID,
		arg.PreferenceKey,
		arg.PreferenceValue,
		arg.UpdatedAt,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.PreferenceKey,
		&i.PreferenceValue,
		&i.UpdatedAt,
	)
	return i, err
}
